### ISSUE TITLE
多说配置的抽离

### ISSUE THREAD

**Issue by aelam** [Huxpro/huxpro.github.io#1]
Fork了你的博客 准备改用你这个主题。 整体设置相对简单
但是发现一些可以优化的地方
* 多说的配置写在post.html模板里面， 这样导致需要更改模板， 配置后 通过include方式
* 对header， footer，navigator可以采用config的形式
* 首页的tag如果支持点击就完美了 
*

**Comment by Huxpro** [comment]
感谢～非常细心：

- 最开始写得时候只是给自己用，所以就 quick and dirty 了，没考虑到 fork 的体验，有空改下哈
- 同上
- 没懂，首页的 tag 指的是？tag 应该都是可以点的吧？

**Comment by aelam** [comment]
首页现在是没有显示tag的， 所以我在想把tag显示出来并可以点击会不会更好

**Comment by Huxpro** [comment]
哦哦没有显示是吧，知道了

**Comment by Huxpro** [comment]
Hey，不好意思平时太忙，久等了。
多说的配置目前已经抽离到 `config.yml`， 可以 checkout 最新的 README 就有

header, footer 属于 include 的部分，由于允许大量自定义，并不适合抽离成通用的配置。
navigator 其实是自动生成的， check 代码就可以看出来

首页目前暂无计划支持 tag，加上去之后可能不够简洁美观～

Nice feedback, thank you

**Comment by aelam** [comment]
赞
