### ISSUE TITLE
标签页在哪里修改呢

### ISSUE THREAD

**Issue by WuKongCoo1** [Huxpro/huxpro.github.io#10]
如题

**Comment by Huxpro** [comment]
您指的是 Tags 页吗？根目录的 tags.html 就是了

**Comment by WuKongCoo1** [comment]
我指得是首页上的  知乎、交互设计 这些导航标签

**Comment by Huxpro** [comment]
哦哦，关于 featured tags，在文档的这里：https://github.com/Huxpro/huxpro.github.io#featured-tags
