### ISSUE TITLE
为什么clone您的模板后格式全是乱的

### ISSUE THREAD

**Issue by MAIHAO1995** [Huxpro/huxpro.github.io#100]
请问，我clone您的模板之后打开是这样的
![image](https://cloud.githubusercontent.com/assets/20553161/17076482/b6291ad8-50e5-11e6-9521-f19ef42e8f28.png)
怎么可以解决这个问题呢？

**Comment by MAIHAO1995** [comment]
我傻x了，不好意思

**Comment by CoXier** [comment]
这个问题怎么解决的呢 @MAIHAO1995
