### ISSUE TITLE
你好, 如果我想增加文章内的目录应该怎么做??

### ISSUE THREAD

**Issue by suzeyu1992** [Huxpro/huxpro.github.io#101]
这个和Hexo还是Jekyll有关系吗,  我是使用hexo的,  按照网上说的添加.
`<div id="toc" class="toc-article">
  <strong class="toc-title">文章目录</strong>
<%- toc(post.content, {list_number: false}) %>
</div>`

并没有效果, 应该怎么办

**Comment by LucasIcarus** [comment]
如果你用的是hexo版本的可以去分支repo提个issue问下...

地址是 https://github.com/Kaijun/hexo-theme-huxblog
