### ISSUE TITLE
非常费解的一个问题

### ISSUE THREAD

**Issue by JaydenHoFly** [Huxpro/huxpro.github.io#102]
win10环境，没有安装jekyll，直接用的大神的模板，发现一个问题：
只要markdown文章中头部的tags配置不是复制的大神原有文章中的，那么push到github后就解析不了，文章链接变成：https://jaydenhofly.github.io/2016/08/06/2016-08-06-optional/
如果是复制的，但是tags数量超过3个，也会出现如上情况，调了好久才发现是这个问题，这是什么原因呢？

**Comment by LucasIcarus** [comment]
你给出的blog地址现在可以正常访问啊..  只是地址与你给出的链接不同, 看起来像是md文件名的问题.. 

然后本地调试最好还是做一下, win10搭建相应的开发环境请参考以下链接: http://jekyll-windows.juthilo.com/

**Comment by nahsum** [comment]
请问楼主博客中的404页面如何定位到自己的博客呢？找了半天没有找到，谢了
