### ISSUE TITLE
用jekyll在本地查看与实际效果不一致怎么办

### ISSUE THREAD

**Issue by ghost** [Huxpro/huxpro.github.io#103]
用jekyll在本地查看无论图片还是字号都要偏小，实际效果是上面的背景图片占了大半屏幕，字体也放大了很多，请问如何解决

**Comment by LucasIcarus** [comment]
F12看下控制台有没有报错..  注意下引入的CSS文件的路径及名称是否正确

最究极的办法就是本地和server端同时审查元素对比样式了..

**Comment by shikiGitHub** [comment]
Mixed Content: The page at 'https://shikigithub.github.io/' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css'. This request has been blocked; the content must be served over HTTPS.
有很多类似这样的错误，请问该如何解决

**Comment by LucasIcarus** [comment]
更换CDN引入的CSS文件的协议前缀, 从http换到https就好了 或者换成本地文件..

**Comment by gyj1109** [comment]
staticfile的服务不支持https，可以试一下bootcdn的服务：

> //cdn.bootcss.com/font-awesome/4.6.3/css/font-awesome.min.css

该地址可以自适应http或https，速度也不错
