### ISSUE TITLE
文章详情页的Catalog很长，则显示不完整也无法滚动

### ISSUE THREAD

**Issue by shinyzhu** [Huxpro/huxpro.github.io#104]
我有一篇文章内容比较多，Catalog的内容也很长，导致页面上无法完整显示Catalog。
地址：http://shinyzhu.com/2016/08/11/dynamo-amazons-ha-kv-store-ZH/

**Comment by gyj1109** [comment]
请问“无法完整显示”是指什么？Catalog可以滚动，在我这儿没问题

**Comment by shinyzhu** [comment]
@gyj1109 您好，我用的OSX的Safari和Chrome都看过。在我这里Catalog只能显示到4.8.2，但是文章看到4.8.2之后的内容catalog没有跟着往上滚动。

**Comment by gyj1109** [comment]
![screenshot_20160811_164600](https://cloud.githubusercontent.com/assets/11223244/17583351/1f1dad2c-5fe3-11e6-9ff5-bd1f0bb651c0.png)
Catelog不会自动随文章进度滚动，将鼠标移到Catalog区域上滚动滚轮即可查看下方内容

PS：我这儿高分屏上100%的缩放可以看到全部 :simple_smile:

**Comment by shinyzhu** [comment]
@gyj1109 好的，感谢，就是觉得OSX很难捕捉到Catalog的滚动区域，经常滚动的时候仍然滚动的文章内容。

**Comment by LucasIcarus** [comment]
Hux好像最近很忙...
等我找到工作考虑把它改一改....
谢谢反馈...

**Comment by shinyzhu** [comment]
@LucasIcarus 谢谢啦，我自己也先看看。感谢你们：）cheers

**Comment by Mensu** [comment]
@shinyzhu 我尝试着看能否解决您这个问题。这里是您那篇文章[在我这里的效果](https://mensu.github.io/2016/08/11/test-long-catalog-dynamo-amazons-ha-kv-store-ZH.html)

**Comment by shinyzhu** [comment]
@Mensu 太酷了！问题解决：）非常感谢！

**Comment by Missmiaom** [comment]
@Mensu 请问我的为什么没有catalog呢，我找了好久，而且把整个项目重新布置了一下还是不行。。。  不是太懂前端的东西，能帮我看一下吗。。。http://leiym.com/2016/12/19/effective_C++/   主页下面有我的github地址，可以在里面找到博客项目。

**Comment by Voleking** [comment]
@Missmiaom 
博文前面要加上
`catalog:    true`

**Comment by Missmiaom** [comment]
@Voleking   太感谢啦~

**Comment by Huxpro** [comment]
Let me confirm the issue here. The issue is: 
Catalog titles got neglected when overflowed

**Comment by withgakki** [comment]
@Mensu  ... 主要是觉得那个滚动条不好看emmmm
