### ISSUE TITLE
Liquid告警

### ISSUE THREAD

**Issue by figofuture** [Huxpro/huxpro.github.io#105]
Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 58): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/keynote.html
    Liquid Warning: Liquid syntax error (line 139): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/keynote.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 58): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/keynote.html
    Liquid Warning: Liquid syntax error (line 139): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/keynote.html
    Liquid Warning: Liquid syntax error (line 148): Unexpected character # in "{{# each}}" in /Users/administrator/projects/huxpro.github.io/_posts/2016-02-01-React-vs-Angular2.markdown
    Liquid Warning: Liquid syntax error (line 61): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 159): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/post.html
    Liquid Warning: Liquid syntax error (line 58): Unexpected character & in "site.duoshuo_share && site.duoshuo_username" in /_layouts/keynote.html
    Liquid Warning: Liquid syntax error (line 139): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/keynote.html
    Liquid Warning: Liquid syntax error (line 38): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/page.html
    Liquid Warning: Liquid syntax error (line 87): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/page.html
    Liquid Warning: Liquid syntax error (line 38): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/page.html
    Liquid Warning: Liquid syntax error (line 87): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/page.html
    Liquid Warning: Liquid syntax error (line 38): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/page.html
    Liquid Warning: Liquid syntax error (line 87): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/page.html
    Liquid Warning: Liquid syntax error (line 38): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/page.html
    Liquid Warning: Liquid syntax error (line 87): Unexpected character { in "tag[1].size > {{site.featured-condition-size}}" in /_layouts/page.html

**Comment by imbedinlove** [comment]
语法错误:
 "site.duoshuo_share && site.duoshuo_username" 修改成 "site.duoshuo_share and site.duoshuo_username"
"tag[1].size > {{site.featured-condition-size}}" 修改成  "tag[1].size > site.featured-condition-size"

参考Liquid 语法 : http://alfred-sun.github.io/blog/2015/01/10/jekyll-liquid-syntax-documentation/
我也今天才折腾这个, 遇到一样的错误, 不保证完全正确, 希望能起作用.

**Comment by bianergege** [comment]
不知道是不是jekyll语法随着版本更新而更新，我用jekyll v3.2.1是跟你报一样的错，但是用jekyll v3.1.3的话，就没有错误了，啊哈哈

**Comment by tobyforever** [comment]
上面@imbedinlove说得对 我是jekyll 3.3版本

**Comment by Huxpro** [comment]
@figofuture @imbedinlove @bianergege @tobyforever 

根据 <https://github.com/github/pages-gem>, Github Pages 目前使用的是 Jekyll 3.0.2，so...let's the only version I targeted at.

**Comment by Huxpro** [comment]
But It should be documented, so thx for reports!

**Comment by andevele** [comment]
经过修改，@imbedinlove说的是正确的

**Comment by dusmart** [comment]
jekyll v3.3.1 ubuntu16.04 出现了liquid warning

**Comment by MingfeiPan** [comment]
try "and" install of "&&"

**Comment by Huxpro** [comment]
Fixed. Thx folks ;)
