### ISSUE TITLE
在网站使用 HTTPS 时 footer.html 中的按钮无法自动加载

### ISSUE THREAD

**Issue by Yitar** [Huxpro/huxpro.github.io#11]
浏览器提示不安全的脚本，如果加载了脚本 就无法使用 HTTPS 了。。。。。
另外建议换种 highlight 自带的好丑啊……

**Comment by Huxpro** [comment]
因为国内的 CDN 很多都还不支持 HTTPS，所以相关资源肯定都会 ` This request has been blocked; the content must be served over HTTPS.`

至于 highlight，使用的是 highlight.js 的 github 风格，你可以自己在 `footer.html` 里替换这个 css：
```
 <link href="http://cdn.bootcss.com/highlight.js/8.6/styles/github.min.css" rel="stylesheet">
```

**Comment by Yitar** [comment]
CloudFlare的CDN貌似不错的
