### ISSUE TITLE
如何控制代码区中tab长度

### ISSUE THREAD

**Issue by zealerww** [Huxpro/huxpro.github.io#113]
rt 代码区tab长度过长

**Comment by LucasIcarus** [comment]
使用
```js
"
```<语言名>
```
"
```
这种格式解析出来的代码区域有问题嘛?  有没有参考网页?

**Comment by zealerww** [comment]
@LucasIcarus 

http://zealerww.github.io/2016/07/07/sqrt/

tab长度过长，8

**Comment by Voleking** [comment]
@zealerww 制表符为8是最常用最普遍的设置，所以为了不在打印或者一些地方显得挺突兀还是最好考虑空格替换 tab

**Comment by Huxpro** [comment]
@zealerww 
这是你自己 markdown 原文件的设置：<https://github.com/zealerww/zealerww.github.io/edit/master/_posts/2016-07-07-sqrt.markdown>

如果不理解 Tab 的原理，可以用空格。
