### ISSUE TITLE
The problem has already been solved

### ISSUE THREAD

**Issue by fairyly** [Huxpro/huxpro.github.io#118]
The problem has already been solved

**Comment by LucasIcarus** [comment]
额, 充分利用搜索工具自学一下?

https://www.google.com/#q=github%E9%83%A8%E7%BD%B2%E4%B8%AA%E4%BA%BAblog

**Comment by ReidHolmes** [comment]
fork之后改成YourName.github.在经过修改即可。。或者不用Fork.，把文件直接部署到你gitgub

**Comment by fairyly** [comment]
我在Windows环境下装jekyll一直提示错误，就是不行额，我用hexo 搭建都没问题的，部署到github也没问题的，就是jekyll不行

**Comment by fairyly** [comment]
今天终于在本地把jekyll折腾好了
