### ISSUE TITLE
Baseurl not works

### ISSUE THREAD

**Issue by FrancoCotter** [Huxpro/huxpro.github.io#12]
标签页的路劲不对，我在config.yml文件中，将baseurl改成了我的项目名字baseurl:'/blog',可是当我访问我的主页时候，可以正常显示，就是点选featured tags时，github pages就404，这个问题该如何解决呢？

**Comment by Huxpro** [comment]
Hi @FrancoCotter 

Thanks to report this bug! I am not using `baseurl` in my blog so it lack testing, sorry about that.
Im already fixed that in latest commit, with a bit of other tiny fixed about `baseurl`, please merge it and tell me if this issue solved or not.

**Comment by FrancoCotter** [comment]
@Huxpro ,黄玄，你好，我没有合并你的代码，我只是看看你修改了哪些，然后我照着修改，因为我把你的多说评论去掉了，但结果却不尽如人意，在本地查看同样出现那个错误，右边的featured tags下面没有tag，进入博客页面点选tag也出现了404的页面，但是我已经加上了site.baseurl了，这是什么原因呢？

**Comment by Huxpro** [comment]
@FrancoCotter  Dont worried.

关于 Tags 点击后 404 的问题，已经 fixed，还是因为我疏忽了 `{{ site.baseurl }}`，Sorry
关于 featured tags 下面没有 tag 的原因，我猜想是因为你的 Tag 因为文章不够都被过滤掉了，其过滤规则默认为 `>1`，可在 `config.yml` 中配置。这块内容在 [文档的 Featured Tags 章节](https://github.com/Huxpro/huxpro.github.io#featured-tags) 里有详细叙述

**Comment by FrancoCotter** [comment]
这些就行了，谢谢黄玄

**Comment by Huxpro** [comment]
@FrancoCotter 

Enjoy! Really thanks to report this bug! I gonna close this issue
