### ISSUE TITLE
怎么自己添加特色Tags

### ISSUE THREAD

**Issue by ReidHolmes** [Huxpro/huxpro.github.io#121]
好像只能添加博主自己之前存在的FEATURED TAGS
求解。。。

**Comment by Voleking** [comment]
Tag 是可以在自己的 post 里面添加的，FEATURED TAGS 我记得好像是要 tag 出现一定次数才会显示，具体可以自己看看代码

**Comment by ReidHolmes** [comment]
嗯...Thank you........
