### ISSUE TITLE
文章内最右侧会多出一个滚动条

### ISSUE THREAD

**Issue by CodeLadyJJY** [Huxpro/huxpro.github.io#123]
jekyll版本3.2.1，win8，本地测试时文章内最右侧会多出一个滚动条
![bug](https://cloud.githubusercontent.com/assets/15910376/19584436/f95b2bc0-9776-11e6-8f10-7e12f4524951.png)

**Comment by liuwang** [comment]
我也遇到了此问题，

**Comment by zrdthu** [comment]
在css里面把`article`设置成 `{overflow: hidden}`就好了

**Comment by jason--liu** [comment]
具体改哪个文件啊,新手还请指教.@zrdthu

**Comment by corcd** [comment]
修改 catalog 的样式即可，原来的有点问题

**Comment by jason--liu** [comment]
请问怎么修改啊,@corcd

**Comment by jason--liu** [comment]
请问如何修改catalog样式？@corcd

**Comment by zrdthu** [comment]
找到`css`文件夹里的`hux-blog.css`和`hux-blog.min.css`，找到里面的
    
    article {
        overflow-x: hidden;
    }

改成

    article {
        overflow: hidden;
    } 

他本来的设置是横向溢出不显示，改成横向纵向都不显示就好了

@jason--liu
