### ISSUE TITLE
请教一下大家，买了域名怎么发布网站

### ISSUE THREAD

**Issue by 405755490** [Huxpro/huxpro.github.io#125]
各位前辈指导一下，我在新网买了一个域名，然后在域名DNS那里（CNAME那一栏）设置了我的gitbug网站，也修改了github网站的cname文件为我的域名。

        现在的问题是：我的域名可以ping通，github网站也可以ping 通，输入域名网址就打不开，输入github网址直接跳转到我的域名了，也是打不开...不知道还需要做什么

**Comment by 405755490** [comment]
有知道的前辈麻烦指导一下哈...

**Comment by BruceZhaoR** [comment]
@405755490  新买的域名，一般24小时跳转才会生效。 等等吧~ 明天再试试看。
