### ISSUE TITLE
about中多说评论代码处data-thread-id的值从哪里得到？

### ISSUE THREAD

**Issue by andevele** [Huxpro/huxpro.github.io#129]
在about.html中关于多说评论的代码，data-thread-id变量的值从哪里得到？随便写一个么

**Comment by andevele** [comment]
随便写了一个id号，现在可以使用了。应该是唯一的id号，和data-thread-key的意思一样。

**Comment by Huxpro** [comment]
@andevele 

由于当时多说数据库迁移的问题，我的评论有部分丢失，所以使用 id 强行索引回来的。
你并不需要使用这个 id，正常情况下，使用 key 就可以与其它文章区分了

关于 data-thread-key， 具体可以参见 <https://github.com/Huxpro/huxpro.github.io/issues/33>
