### ISSUE TITLE
在post中，能否支持markdown的目录（右侧），和一个回到最上的按钮？

### ISSUE THREAD

**Issue by chenjian158978** [Huxpro/huxpro.github.io#137]
1. 在markdown中添加 [toc]，便可以**生成目录**。
这个目前不能在博客中看到，是否能支持？如果支持的话，能否已到右侧，随着文章的下滑自动下滑；

2. 在后侧同时加个**回到最上**的按钮？

**Comment by Ethan0w0** [comment]
+1

**Comment by chenjian158978** [comment]
@Ethan0w0
其实他的博客中包含了“右侧目录”这个功能。
建议：
1. 仔细看楼主的博客代码；
2. 可以参考我的博客[o-my-chenjian.com](https://o-my-chenjian.com)

**Comment by ZzSean** [comment]
请问怎么添加的？我post里面catalog设置的true 还是不行

**Comment by jason--liu** [comment]
我在catalog里面设置了true也是不行，楼上解决了吗？@ZzSean

**Comment by ZzSean** [comment]
@jason--liu #212 这里有解答

**Comment by Huxpro** [comment]
hope #212 can solve your concerns ;)
