### ISSUE TITLE
[2017-01-01 00:57:29] ERROR `/sw.js' not found.

### ISSUE THREAD

**Issue by xuwanjin** [Huxpro/huxpro.github.io#139]
点击网页是出现了[2017-01-01 00:57:29] ERROR `/sw.js' not found.  时间和本地的不同步, 还有sw.js文件找不到. 同时本地和网络上都无法出现文章

**Comment by xuwanjin** [comment]
找出来原因了, 写错路经了, _post写成了_posts了. 粗心了

**Comment by Donng** [comment]
请问具体是哪里写错了路径，我也出现了这个错误。刚下载的模板并没有修改什么东西
