### ISSUE TITLE
How to set Keynote blog link just like js-module-7day?

### ISSUE THREAD

**Issue by MrFuFuFu** [Huxpro/huxpro.github.io#14]
I see you blog 《JAVASCRIPT MODULARIZATION SEVEN DAY JavaScript 模块化七日谈》link is http://huangxuan.me/js-module-7day/#/ ，my blog theme [mrfu.me](http://mrfu.me/) is use your theme.
I will be in the team for technology sharing, and I see your Keynote sharing tools are great. 

I see your Keynote great, but I don't know how to add to my blog. Such a link with you http://huangxuan.me/js-module-7day/#/  
Could you teach me.

**Comment by Huxpro** [comment]
@MrFuFuFu 
Maybe [the 'keynote-layout' section of document](https://github.com/Huxpro/huxpro.github.io#keynote-layout) helps

**Comment by MrFuFuFu** [comment]
好吧，我再用中文表述一下~可能我英文没表达明白，我的意思是 你的这篇文章的链接是 http://huangxuan.me/js-module-7day/#/ 这个，然后我想让我的 https://github.com/MrFuFuFu/rxjava-keynote 这个 Keynote 也能像你这样能通过类似的链接访问到，就像这样 http://mrfu.me/rxjava-keynote/#/ 的形式。我不知道怎么让这个链接指向我要的Keynote 页面，嗯。。我博客的写法和你是完全相同的。嗯。。明天就要公司内部分享了。能帮我看一下吗？

**Comment by Huxpro** [comment]
@MrFuFuFu  All right, I got it!

Pay attention to [my keynote's repo](https://github.com/Huxpro/js-module-7day), there is a `gh-pages` branch there, which works just as github pages and It serves your keynote repo under your github.io domain.

It's deathly simple to do that:

```bash
$ git push origin master:gh-pages
```

After that you can access `mrfu.me/rxjava-keynote/` now!

**Comment by MrFuFuFu** [comment]
Cool, It's succeeded. Thank you so much for your help.
