### ISSUE TITLE
如何在代码块中显示行号

### ISSUE THREAD

**Issue by andevele** [Huxpro/huxpro.github.io#140]
在本地编辑器编写代码时，用markdown加入了行号，预览时可以正常显示，但是放到huxpro中行号就没有显示，如何加入行号

**Comment by Huxpro** [comment]
@andevele I just randomly google `jekyll code line numbers` and the result includes issues like https://github.com/jekyll/jekyll/issues/4619 which you should check out ;)

BTW Welcome to contribute back!

**Comment by Huxpro** [comment]
Done via [v1.8](https://github.com/Huxpro/huxpro.github.io#v18)
