### ISSUE TITLE
【已解决】想问下标题左侧#如何去除呢？

### ISSUE THREAD

**Issue by amilyk** [Huxpro/huxpro.github.io#145]
> 不懂css,js

问题：
html的标题形式or##markdown形式
![markdown](https://cloud.githubusercontent.com/assets/15701499/22829937/b9ac2d0a-efdf-11e6-9e33-be74f2a3d956.png)

显示：标题都左侧都有 #
![pro](https://cloud.githubusercontent.com/assets/15701499/22829942/bf39082e-efdf-11e6-981e-62471fd5d79e.png)

**Comment by amilyk** [comment]
参考#136修改后，不过，若是本地还要重启服务~

**Comment by Huxpro** [comment]
#136
