### ISSUE TITLE
代码显示问题

### ISSUE THREAD

**Issue by hooting** [Huxpro/huxpro.github.io#15]
我不是很懂模板的设计，想问一下，当一行代码的长度超过宽度时，使用滚动条显示，而不是自动换行。自动换行在有些情况下会很丑。

![image](https://cloud.githubusercontent.com/assets/1594517/11037365/5a5dc86a-8738-11e5-883b-5d1a44d40da8.png)

**Comment by MrFuFuFu** [comment]
好问题！

**Comment by Huxpro** [comment]
@hooting @MrFuFuFu  

Problem solved! [COMMIT - improve code>pre style to fixed issue#15](https://github.com/Huxpro/huxpro.github.io/commit/a1b6468cf3e1469438b1b05bfa5d9de39460fa36)

Now, all `<code>` block is self-adaptive to the max-width of the code, which display a scroll-bar when overflow and never wrap!  

*But, still, do not write too much code in one line ;)*

**Comment by MrFuFuFu** [comment]
cool, I've updated your modified code. very thank you.
