### ISSUE TITLE
footer只显示了知乎

### ISSUE THREAD

**Issue by kodyan** [Huxpro/huxpro.github.io#150]
配置了微博、Github、知乎，push到GitHub Pages只显示了知乎。

see [https://kodyan.github.io](https://kodyan.github.io)

**Comment by renchao0711** [comment]
请问您怎么解决了这个只显示部分图标的问题。

**Comment by lihanxiang** [comment]
同问，配置了知乎，github， 就显示了一个 知 字

**Comment by Huxpro** [comment]
Should be fixed now
