### ISSUE TITLE
报错/layout.post.html里面有“错误的字符”,但是可以正常的跑起来

### ISSUE THREAD

**Issue by fengzhao** [Huxpro/huxpro.github.io#152]
![image](https://cloud.githubusercontent.com/assets/6206340/23958759/11aabcfc-09de-11e7-84c2-8e439171c700.png)

定位到是这个位置了，检查了很久，没发现问题

**Comment by fengzhao** [comment]
?

**Comment by ysgxm** [comment]
try this  http://stackoverflow.com/questions/39688902/liquid-warning-liquid-syntax-error-unexpected-character-when-i-jekyll-serve

**Comment by Huxpro** [comment]
duplicated #221

**Comment by fengzhao** [comment]
> duplicated #221

已经迁到hexo了，不过还是谢谢你的repo。
