### ISSUE TITLE
请问portfolio 里面的内容怎么添加呢

### ISSUE THREAD

**Issue by tuohuang** [Huxpro/huxpro.github.io#155]
新建了一个portfolio之后里面的内容是空的，然后需要怎么操作才能添加内容呢

**Comment by SIGAOYI** [comment]
我用的本办法，找到内控卡片的DIV，复制之。
![wechatimg2](https://cloud.githubusercontent.com/assets/20675570/24580147/872930c6-1735-11e7-922f-3b1b8ddb595d.jpeg)

**Comment by tuohuang** [comment]
谢谢
