### ISSUE TITLE
Chinese Document

### ISSUE THREAD

**Issue by Huxpro** [Huxpro/huxpro.github.io#16]
Volunteer needed.

**Comment by Captain-D** [comment]
I just build up a blog based on your code ~

In order to thank you, let's do it ?

**Comment by Huxpro** [comment]
@DavexPro 

Hey that's discuss here. Again, It would be so so great that you can help me to do that!

In my opinion, you can fork [Huxblog-Boilerplate](https://github.com/Huxpro/huxblog-boilerplate) instead of this repo, seeing the boilerplate is separated from my personal update so It's far more stable.

You can create something like `README-zh.md` in the root or a `docs/` and after you finish it and we finish the review of the pull request, It will be merged both in boilerplate and this repo ;)

**Comment by DavexPro** [comment]
Alright, I did it, and what should I translate?

All based on the README.md ? or you will feed me some new features?

**Comment by Huxpro** [comment]
@DavexPro  Well...all feature is already there I thought. OTZ
You can just do translation actually. But if you have some new idea about that Im definitely welcome

**Comment by DavexPro** [comment]
Ahaha I am working on it @Huxpro 

P.S. There will be some tricks word I can not translate well, and I definitely need you hand~ ORZ

**Comment by Huxpro** [comment]
@DavexPro Awesome 🙌🙌🙌🙌
Sure, may also something wrong with my expression, so feel free to ask me here or in mail.
