### ISSUE TITLE
ServiceWorker registration failed:  DOMException

### ISSUE THREAD

**Issue by lishoulong** [Huxpro/huxpro.github.io#160]
Hi, Hux，有个问题请教一下，因为我的custom域名是http的，导致sw install失败，但是github pages项目中提到，“Https unavailable for your site because you have a custom domain configured”，看到你的custom域名协议是https的，不知道你是怎么解决这个问题的？

**Comment by AndyBernie** [comment]
用cloudflare解析你的域名，加密选择flex

**Comment by lishoulong** [comment]
好的，我试试，多谢哈
