### ISSUE TITLE
github更新了jekyll3后强制使用rouge语法高亮

### ISSUE THREAD

**Issue by wangjiachun** [Huxpro/huxpro.github.io#166]
github更新了jekyll3后强制使用rouge语法高亮，如果采用模板默认的风格是白色背景
我的问题是，如果我要自定义这个颜色设置应该如何做？
我试过导入另外一个rouge.css文件替换原来的syntax.css，但是效果跟实际情况有差别，比如好多代码颜色跟背景接近导致辨认不出，还有插入行号的时候也会出现混乱，有什么好的trick吗？

**Comment by jiyuefeng** [comment]
http://jwarby.github.io/jekyll-pygments-themes/languages/java.html

**Comment by Huxpro** [comment]
https://github.com/Huxpro/huxpro.github.io#how-can-i-customize-the-theme-of-code-block
