### ISSUE TITLE
没有SSH秘钥如何使用你的模板:)

### ISSUE THREAD

**Issue by rorschach** [Huxpro/huxpro.github.io#17]
正克隆到 'huxblog-boilerplate'...
Enter passphrase for key '/root/.ssh/id_rsa':

**Comment by Huxpro** [comment]
呃，如果您不把 ssh 私钥放到 github 的话，您也无法使用 Github Pages 呢 😢

**Comment by hooting** [comment]
用https clone

**Comment by rorschach** [comment]
我对github不是很熟练，其实我有自己的ssh key,但是我以为要用你的T_T,意思是用我自己的就可以了吗？@Huxpro

**Comment by rorschach** [comment]
其实我试过这种方法，但是好多东西要删，好麻烦，所以想只用模板@hooting

**Comment by hooting** [comment]
​只用模板，把原来的repository 下载， 删除原来的_post内容，把自己的博文内容放入，并push至自己的XXX.github.io
repository就可以了啊。不需要删很多啊​

*祝好！*
*刘华艇*

2015-11-20 10:03 GMT+08:00 rorschach <notifications@github.com>:

**Comment by rorschach** [comment]
我还删除了一些图片以及其他不记得的东西
现在是这样的  rorschach.github.io

**Comment by Huxpro** [comment]
@rorschach 关于如何将 ssh_key 放到 github，有[官方的教程](https://help.github.com/articles/generating-ssh-keys/)

，如果您觉得不知道怎么修改的话，也可以直接下载准备好了的 [Boilerplate](https://github.com/Huxpro/huxpro.github.io#boilerplate-beta)
