### ISSUE TITLE
请问site.pages是在哪里设置查看

### ISSUE THREAD

**Issue by suihansongmao** [Huxpro/huxpro.github.io#171]
首先，非常感谢博主，很漂亮！
       然后，我有一个小问题：我想修改导航的menu，于是就找到nav.html文件，准备修改。发现是循环site.pages来输出菜单的，但我找遍了整个工程还是没发现这个东西在哪里，所以想请问这东东在哪里设置啊？跪求！

**Comment by bianergege** [comment]
建议去jekyll官网了解下 [https://jekyllrb.com/](url)
![image](https://cloud.githubusercontent.com/assets/8177483/26768734/8326515a-49dc-11e7-92f8-a30f09239b65.png)

**Comment by xuepro** [comment]
我也想知道，只给了链接没任何用处

**Comment by xuepro** [comment]
我也想知道，只给了链接没任何用处
上面的图site variables在哪里？

**Comment by xieshuaix** [comment]
修改nav里的页面标题的话只需在相应的页面.html里的page info里修改title

**Comment by nancybaby002** [comment]
https://jekyllrb.com/docs/variables/#site-variables

site.pages是自动生成出来的…

**Comment by Huxpro** [comment]
`site.pages` is autogenerated by traversing `*.html` at root dir.
