### ISSUE TITLE
关于背景图片设置

### ISSUE THREAD

**Issue by advpetc** [Huxpro/huxpro.github.io#173]
Hello!非常感激作者可以提供这么酷炫的模版，五体投地！

想问一个小问题，请问你是在哪里找到这些尺寸刚好的照片的？还是说用了ps等工具crop成1900*870的？小白一个，希望能回答。

**Comment by DerekKen** [comment]
1. 可以自行用工具crop；
2. 直接使用尺寸大于1900*870的图片也是完全OK的，会自动裁剪，只是可能达不到你的预期效果；
3. Google和Baidu的图片搜索都是可以精确指定尺寸的，只是很可能找不到你想要的图片；
