### ISSUE TITLE
想问问这个paginator

### ISSUE THREAD

**Issue by DogeWatch** [Huxpro/huxpro.github.io#18]
fork下来发现首页没有文章列表，把paginator改成site才有，但是没有分页了，这是怎么回事呢

**Comment by Huxpro** [comment]
@DogeWatch 不应该啊……您可以试试直接 clone Boilerplate

**Comment by HarryFight** [comment]
这个问题，我今天也遇到了。  
1. 在编译的时候有个报错提示找不到 `XX    gems: [jekyll-paginate]   XX`。
2. 按照它的意思在 `_config.yml`里面加上了这个配置。
3. 再次运行的时候 可能会提示里 没有安装 `jekyll-paginate`。这个时候就运行 `gem install`安装下这个东东，然后就可以了。

**Comment by Huxpro** [comment]
@HarryFight 
OK 我明白了，这个应该是你本地环境的问题，与我这边的代码倒是无关。
可能是你 `gem install jekyll` 时没有带上这个依赖，所以本地编译会报错，如果上传到 Github Pages 的话，github 这边的环境是有安装这个依赖的

**Comment by HarryFight** [comment]
@Huxpro 恩 是这样的  那天踩坑后 解决了
