### ISSUE TITLE
控制台运行时会提示Liquid语法的错误

### ISSUE THREAD

**Issue by ITGrocery** [Huxpro/huxpro.github.io#182]
![image](https://user-images.githubusercontent.com/10252344/29740943-30f47bec-8a95-11e7-9266-55e62efaf7df.png)

引用.config.yml中的配置时不需要添加两层花括号。
```
{% if tag[1].size > site.featured-condition-size %}
```

**Comment by XiaomoWu** [comment]
经测试，的确删除两个花括号时报错就会消失。版本是最新的v1.5.2，master分支。

**Comment by Huxpro** [comment]
Thx. Fixed ;)
