### ISSUE TITLE
关于WordPress使用你主题所遇到的问题：

### ISSUE THREAD

**Issue by Pgrammerybj** [Huxpro/huxpro.github.io#184]
我把您这个工程拉下来后直接放到了我WordPress  htdocs/wp-content/themes/huxpro.github.io-master 下，然后f't'p上传，但是WordPress的控制台却 提示 ：

名称                                 | 图像描述 |   |  
-- | -- | -- | --
huxpro.github.io-master | 缺少样式表。

这个项目能直接在Wordpress中使用吗？
期待您的回复。

**Comment by SIGAOYI** [comment]
http://www.jianshu.com/p/01da26087155 <http://www.jianshu.com/p/01da26087155>



Kind Regards
Axe龟

在 2017年8月31日，01:37，杨保疆 <notifications@github.com> 写道：

我把您这个工程拉下来后直接放到了我WordPress htdocs/wp-content/themes/huxpro.github.io-master 下，然后f't'p上传，但是WordPress的控制台却 提示 ：

名称	图像描述	 	 
huxpro.github.io-master	缺少样式表。		
这个项目能直接在Wordpress中使用吗？
期待您的回复。

**Comment by Huxpro** [comment]
I doubt it.
This blog is built for GitHub-page, which uses Jekyll and it's written in Ruby.
One solution might be:

1. build the site with Jekyll 
2. use the generated `_site` as static files in your WordPress

But when you need to update (e.g. `.md`), you have to rebuild and sync it manually 😢
