### ISSUE TITLE
怎么定制化portfolio页面？

### ISSUE THREAD

**Issue by Missmiaom** [Huxpro/huxpro.github.io#194]
请前端大佬们指条路，怎么定制化portfolio页面，比如我想做成一个摄影的记录，可以和博客一样通过写markdown来创建文章，能不能使用其他的模板添加到项目里呢。

**Comment by Huxpro** [comment]
portfolio 只是一个静态页面
随便什么都可以的

**Comment by Missmiaom** [comment]
@Huxpro 感谢大佬，我对前段不太熟诶，但我是程序员有一定基础，能不能麻烦大佬提供几个关键字，然后我去实现我想要的功能呢
