### ISSUE TITLE
评论，Tag，Code 的问题

### ISSUE THREAD

**Issue by MrFuFuFu** [Huxpro/huxpro.github.io#2]
你好，想 fork 你的主题，哈哈，很棒的主题，
嗯，好吧，前端方面我是小白，所以，想提几个问题。
1. 我不需要评论，怎么彻底去掉评论叻。因为....不会有这么多人评论的，因为没这么多人访问，哈哈。
2. 我不需要统计，怎么彻底去掉统计叻。因为....同上....
3. 我不需要 Tag，怎么彻底去掉 Tag了。因为....同上...
4. 因为 blog 很多都是 code，所以，代码块的颜色优化我该怎么做呢？
5. 你真棒

[MrFu-傅圆的个人博客](http://mrfufufu.github.io/)

**Comment by Huxpro** [comment]
啊哈～收到了，我看看是写个文档还是怎么弄下好啦

**Comment by MrFuFuFu** [comment]
@Huxpro 好啊好啊，那你加油写~写完我就能移过去了

**Comment by MrFuFuFu** [comment]
@Huxpro hello 第四个问题解决了，原来是我之前写的时候使用了大写的，改成小写的就对了
`xml`
`XML`

**Comment by Huxpro** [comment]
Hey, sorry for the wait.
I check out your blog and just found you seems already solve your problems. Congratulation!

The Comments part is already drawn out into the `_config.yml` and you can just checkout the new README.
Analysis part is still TODO seeing my procrastination...but it seems like you already figure out so I can assume the comments between the code take effect..

I thought **Tag Support** is one of the most awesome part of this theme so I recommend you keep it.

Thank you for your nice feedback!

**Comment by MrFuFuFu** [comment]
@Huxpro  Hi,Very thanks you.

About question 1, 2, 4, I have resolved them, Yes, I decide to keep the Tag Support, I also consider that it is awesome part of this theme. 
Finally, thank you to communicate with me in English.

**Comment by Huxpro** [comment]
Aha, same to u, I also consider that English really plays a essential role in developer skillsets. 
So I just keep using it...although there must be bunch of wrong usage ;(

Im gonna close this issue, thanks for the nice talk~
