### ISSUE TITLE
css等样式表请求不到是什么情况

### ISSUE THREAD

**Issue by upcwxd** [Huxpro/huxpro.github.io#200]
![image](https://user-images.githubusercontent.com/33097631/32132076-2aef13b6-bbef-11e7-87f9-a22582aeadf3.png)
但是我在仓库里看的到这个资源

**Comment by upcwxd** [comment]
知道了，是设置baseurl又设置了一层，路径错了

**Comment by youngbeom-shin** [comment]
@upcwxd 请教一下是如何解决的呢 遇到了同样的问题 不胜感激！
