### ISSUE TITLE
关于Trusted Domains

### ISSUE THREAD

**Issue by fibears** [Huxpro/huxpro.github.io#21]
你好，我想问一下，如何设置多说的域名白名单呢？
我在多说后台的域名白名单中添加了自己博客的地址，可是发现评论框无法显示了，请问这是啥情况呢？
谢谢。

**Comment by Huxpro** [comment]
@fibears 

如果您已经把 `config.yml` 里的 duoshuo 账号替换成了你的 short_name 的话，这个设置应该很简单就能成功的。我的配置如下

```
huangxuan.me
huxpro.github.io
```

如果需要本机调试时也看得到的话，需要额外加上 `localhost`
您可以确认一下设置的对不对

**Comment by fibears** [comment]
可以了，thx!
