### ISSUE TITLE
文章目录 catalog 显示异常

### ISSUE THREAD

**Issue by kobayashicoding** [Huxpro/huxpro.github.io#212]
![屏幕快照 2017-12-01 上午10.45.05.png](https://i.loli.net/2017/12/01/5a20c250bc9b5.png)

文章用了 `#` `##` `###`等md语法进行分段但是无法显示目录

**Comment by jlguochn** [comment]
同样的问题，你解决了吗。

**Comment by jlguochn** [comment]
终于解决了！footer.html下 那段JS
// interop with multilangual 这个注释下面的那个if else语句全部注释掉
下一行的_containerSelector  改成  div.post-container
var P = $('div.post-container'),a,n,t,l,i,c;这样就可以了

**Comment by corcd** [comment]
删除的改法太粗暴了。。。其实修复这个 bug 很简单，将if ({{ page.multilingual }})改成if ("{{ page.multilangual }}")，使其符合语法规范（顺便吐槽一下这个英文的拼写错误。。）即可正常显示 catalog 了

**Comment by kobayashicoding** [comment]
@jlguochn 3q 按照你的方法解决了 不知为何这段判断代码无效果

**Comment by corcd** [comment]
@kobayashicoding 修改成
```js
// interop with multilingual 
        if ("{{ page.multilingual }}") {
            _containerSelector = 'div.post-container.active'
        } else {
            _containerSelector = 'div.post-container'
        }
``` 就可以解决问题了，不用像楼上那么暴力移除（那样会失去中英文 md 转换功能）

错误在于 if 条件没有加双引号，语法错误

**Comment by corcd** [comment]
@kobayashicoding 修改成
```js
// interop with multilingual 
        if ("{{ page.multilingual }}") {
            _containerSelector = 'div.post-container.active'
        } else {
            _containerSelector = 'div.post-container'
        }
``` 
就可以解决问题了，不用像楼上那么暴力移除（那样会失去中英文 md 转换功能）

错误在于 if 条件没有加双引号，语法错误

**Comment by kobayashicoding** [comment]
@corcd 感谢

**Comment by ShenDada** [comment]
@corcd 修正后可以显示目录 请问文章中会有 # 符号存在可以怎么解决？

**Comment by netcmcc** [comment]
@corcd 这个#是主题样式。

**Comment by StandHR** [comment]
@ShenDada 在_config.yml中将anchorjs改false

**Comment by wym3253** [comment]
在修改了footer.html之后目录已经正确显示，但是没有办法跟随页面滑动，请问怎么解决？

**Comment by bigbugbean** [comment]
@corcd 我按照你的方法加了双引号还是没有显示目录，请问还有哪些地方要改的吗

**Comment by SupulooZhao** [comment]
> @corcd 我按照你的方法加了双引号还是没有显示目录，请问还有哪些地方要改的吗

同样也没有显示目录……大神求助~

**Comment by lsdlinshunda** [comment]
> > @corcd 我按照你的方法加了双引号还是没有显示目录，请问还有哪些地方要改的吗
> 
> 同样也没有显示目录……大神求助~

@SupulooZhao 文章头部需要加 `catalog:  true`

**Comment by SupulooZhao** [comment]
> > > @corcd 我按照你的方法加了双引号还是没有显示目录，请问还有哪些地方要改的吗
> > 
> > 
> > 同样也没有显示目录……大神求助~
> 
> @SupulooZhao 文章头部需要加 `catalog: true`

谢谢帮助，我按照您说的在`post.html`和`footer.html`最前面都加上了
```
---
catalog: true
---
```
但是更新后依旧没有反应，连catalog的字样也没出现。和题主情况不一样，我一开始就没有……文章用的是markdown格式，`##`形式的标题，请问能够提供什么信息让您了解更多以便帮忙解决一下我的问题吗？感谢！

**Comment by corcd** [comment]
> > > > @corcd 我按照你的方法加了双引号还是没有显示目录，请问还有哪些地方要改的吗
> > > 
> > > 
> > > 同样也没有显示目录……大神求助~
> > 
> > 
> > @SupulooZhao 文章头部需要加 `catalog: true`
> 
> 谢谢帮助，我按照您说的在`post.html`和`footer.html`最前面都加上了：
> 
> ```
> ---
> catalog: true
> ---
> ```
> 
> 但是更新后依旧没有反应，连catalog的字样也没出现。和题主情况不一样，我一开始就没有……文章用的是markdown格式，`##`形式的标题，请问能够提供什么信息让您了解更多以便帮忙解决一下我的问题吗？感谢！

亲呢这边建议您多了解一下博客的运作原理和语法格式，请将 catalog: true 加入您撰写的 md 文档头部，而不是模板 html 中

**Comment by SupulooZhao** [comment]
> > > > > @corcd 我按照你的方法加了双引号还是没有显示目录，请问还有哪些地方要改的吗
> > > > 
> > > > 
> > > > 同样也没有显示目录……大神求助~
> > > 
> > > 
> > > @SupulooZhao 文章头部需要加 `catalog: true`
> > 
> > 
> > 谢谢帮助，我按照您说的在`post.html`和`footer.html`最前面都加上了：
> > ```
> > ---
> > catalog: true
> > ---
> > ```
> > 
> > 
> > 但是更新后依旧没有反应，连catalog的字样也没出现。和题主情况不一样，我一开始就没有……文章用的是markdown格式，`##`形式的标题，请问能够提供什么信息让您了解更多以便帮忙解决一下我的问题吗？感谢！
> 
> 亲呢这边建议您多了解一下博客的运作原理和语法格式，请将 catalog: true 加入您撰写的 md 文档头部，而不是模板 html 中

哈哈谢谢亲！今天下午我对照着原作者的md文档，发现自己漏了开头的这个catalog: true，加上之后就有了。刚正准备来回复一下“已解决”，没想到您给回复了，我是纯粹的新手哈哈，之后一定会花时间好好看看这方面的知识，感谢！！
