### ISSUE TITLE
为什么博文时间2018年就不显示，2015年就会显示

### ISSUE THREAD

**Issue by Cflelf** [Huxpro/huxpro.github.io#218]
---
layout:     post
title:      "My first blog"
subtitle:   "寒假开始啦"
date:       2018-01-23 15:00:00
就是这里的date，改成2015 _site文件夹会自动生成，2018的话就什么也没

**Comment by StandHR** [comment]
可以不写文章前的date，只要你文件名开头有时间就行

**Comment by Cflelf** [comment]
我看到是TimeZone的问题，我设置成Asia/Shanghai了还是不行，比如现在北京时间2018/1/24，我发的时间改成1/22，23是可以的，但是当天是不行，要到明天才会显示出来

**Comment by StandHR** [comment]
这个我没注意到，不过我习惯不写date，会默认是文件名中的时间，立即就可以显示

**Comment by Cflelf** [comment]
好的，多谢啦，我等会试试
