### ISSUE TITLE
markdown不会绘制表格

### ISSUE THREAD

**Issue by DullCat-c** [Huxpro/huxpro.github.io#219]
首先感谢作者提供模块,其次在模板上并不能显示表格(我的表格在github的预览框是可以显示的),这点非常蛋疼,希望作者尽快解决

**Comment by FeDemo** [comment]
>[https://fedemo.top/2017/12/08/oracle_sql_merger-of-ranks/](https://fedemo.top/2017/12/08/oracle_sql_merger-of-ranks/)   

你写错了吧.....

**Comment by DullCat-c** [comment]
不好意思 我以前在简书上写的,简书的表格语法和github的不一样 (:逃

**Comment by FeDemo** [comment]
>@DullCat-c 
你最好在本地搭个jekyll环境,方便调试以及修改些样式

**Comment by DullCat-c** [comment]
@FeDemo    好的,非常感谢
