### ISSUE TITLE
Markdown内公式无法显示问题

### ISSUE THREAD

**Issue by GuanglinZhou** [Huxpro/huxpro.github.io#230]
如何解决博客内markdown公式无法显示问题？

**Comment by GuanglinZhou** [comment]
<script type="text/javascript" async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"> </script>

markdown文件前加上述js代码，md公式就转换了。但是排版还是不太正常。

**Comment by Huxpro** [comment]
Done via [V1.8](https://github.com/Huxpro/huxpro.github.io#v18)
