### ISSUE TITLE
用的是那个简洁的模板，为什么readme会被当成nav啊？

### ISSUE THREAD

**Issue by SpecialYy** [Huxpro/huxpro.github.io#231]
如图：
![image](https://note.youdao.com/yws/public/resource/3c10d342ddbe33d5a4b711b438faa1a2/xmlnote/E979A2FC30FB4AB0B85E8E6F1FC9636F/4826)

**Comment by SpecialYy** [comment]
没人解决吗？

**Comment by Huxpro** [comment]
可否提供你的代码？不然没有办法帮助你
