### ISSUE TITLE
代码块背景颜色

### ISSUE THREAD

**Issue by Stephan14** [Huxpro/huxpro.github.io#232]
请问怎么设置代码块的背景颜色，在哪一个配置文件中修改，我不是特别懂前端

**Comment by 77QingLiu** [comment]
+1

**Comment by DFVSQY** [comment]
这个让作者添加吧，我通过修过less文件里的代码块颜色效果不尽人意。可以去顶[我提出的问题](https://github.com/Huxpro/huxpro.github.io/issues/244)，希望作者能够看到这个重大需求。

**Comment by Huxpro** [comment]
New code block in [V1.8](https://github.com/Huxpro/huxpro.github.io#v18) was released.
Please check out [FAQ](https://github.com/Huxpro/huxpro.github.io#how-can-i-customize-the-theme-of-code-block) for how to customize code theme

**Comment by 77QingLiu** [comment]
@Huxpro , V1.8 中用pygments theme css覆盖hightlighter.css无法修改code block 背景颜色

**Comment by ssrzz** [comment]
inline code字体(比如改成 Courier New)以及背景颜色怎么改 ？比如下面的。
<img width="206" alt="Screen Shot 2019-07-04 at 8 27 28 PM" src="https://user-images.githubusercontent.com/15714030/60674182-27c07a80-9eac-11e9-984c-a56fe0d33aa9.png">
