### ISSUE TITLE
请问为什么footer的图标都无法显示呢，知乎只有一个‘知’字，github图标没了

### ISSUE THREAD

**Issue by lihanxiang** [Huxpro/huxpro.github.io#235]
![image](https://user-images.githubusercontent.com/25614194/38790120-77976eb8-4171-11e8-9148-20979a21f4b6.png)

**Comment by JYBeYonDing** [comment]
请教不挂域名怎么解决？

**Comment by JYBeYonDing** [comment]
自己来回答一下，吭哧吭哧整了一天，前端是真不懂。。。
其实是由于https不能引用http的资源导致的。
修改href="https://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css"
async("https://cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js"
两个链接就好了

**Comment by Huxpro** [comment]
The current implementation has switched to use `//` rather than `https://`.
It should works fine under either http or https ;)

**Comment by SupulooZhao** [comment]
您好，请问如何添加其它的社交网站？我复制了类似的模块，改了具体的网址链接，生成网页后会出现一个没有logo的灰色圆形，可以点击跳转到目标社交网站，但我不知道如何给它添加对应的logo，文件中没有找到类似.ico的文件，我不太明白如何添加或替换它们。希望您有空能帮我解答一下~

**Comment by Voleking** [comment]
@SupulooZhao 关键词 Font Awesome

**Comment by SupulooZhao** [comment]
好的谢谢！我再去研究研究~萌新刚上手hh

**Comment by SupulooZhao** [comment]
> @SupulooZhao 关键词 Font Awesome

感谢，找到了instagram的logo代码，替换上了，但反色之后好像与原logo不太一样，不知道问题具体在哪里。同时我发现这个库里没有知乎等国内其他社交网站的logo，所以原作者Hux好像在圆形上加了个“知”字代替哈哈，总之谢谢了。

**Comment by laisimiao** [comment]
> 您好，请问如何添加其它的社交网站？我复制了类似的模块，改了具体的网址链接，生成网页后会出现一个没有logo的灰色圆形，可以点击跳转到目标社交网站，但我不知道如何给它添加对应的logo，文件中没有找到类似.ico的文件，我不太明白如何添加或替换它们。希望您有空能帮我解答一下~

我也是，比如想加一个csdn的社交平台链接源码怎么改啊？非常想知道
