### ISSUE TITLE
主题很不错，希望作者能增加Code Block的主题更换和代码行数的支持 。

### ISSUE THREAD

**Issue by DFVSQY** [Huxpro/huxpro.github.io#244]
Jekyll内置的代码行数功能显然有问题，根本就不能用。
希望作者花时间能把代码块的主题更换和代码行数功能增加上就更完美了，就像[本主题的Hexo版本](http://beantech.org/)一样。如下图：
![image](https://user-images.githubusercontent.com/8075421/40308999-9c29a22a-5d3a-11e8-9909-42686beb3fa2.png)

**Comment by Huxpro** [comment]
Done by [V1.8](https://github.com/Huxpro/huxpro.github.io#v18) 💛
