### ISSUE TITLE
时间不同，会导致blog不被编译。

### ISSUE THREAD

**Issue by new-xd** [Huxpro/huxpro.github.io#25]
环境：
win7、jekyll

## jekyll-paginate missing     duplicate [#18](https://github.com/Huxpro/huxpro.github.io/issues/18)
我下了huxblog-boilerplate-master之后， 运行jekyll serve 会有提示

>Deprecation: You appear to have pagination turned on, but you haven't inc
luded the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in yo
ur configuration file.

而且首页没有 blog列表

在_config.yml 中 添加  gems: [jekyll-paginate] 之后 没有这个问题。

## markdown不能生成html
当写的blog中 date如下设置时，

    date:       2016-01-09 18:00:00

_site下不会生成对应的页面。
而有些时间值可以 比如 

    date:       2016-01-09 08:00:00

不知道这是什么情况？！
博主没有遇到过这种情况吗？

**Comment by Huxpro** [comment]
@new-xd  跟这个 issue 应该类似：https://github.com/Huxpro/huxpro.github.io/issues/18

**Comment by new-xd** [comment]
恩 第一个问题是重复的。

第二个问题有解决方案吗？

我又改了下排版，这样清楚点

**Comment by Huxpro** [comment]
@new-xd 第二个问题应该跟 date 值没有关系（除非你格式写错了）；每次在根目录执行 `jekyll build` 时就会做一次生成， `jekyll serve` 则会做一次生成然后起一个服务，你可以再测试下；如果还未能解决可以给我你的仓库地址

**Comment by new-xd** [comment]
我尝试 提交到github上了，可以正常显示。。。。。。
但是在本地 确实不可以。

也就是说，我本地的jekyll环境有问题。

**Comment by new-xd** [comment]
我这边的能显示出来的blog， post时间解析 也 稍有问题，

    2016-01-08 23:00:00

这样的时间 会被解析为 1月9日

**Comment by Huxpro** [comment]
@new-xd 你看一下你的文件标题

**Comment by new-xd** [comment]
发现了一个讨论这个问题的[issue](https://github.com/jekyll/jekyll/issues/1069)
是 时区 有问题，时间值加上时区信息就不会有错

    date:       2016-01-09 18:22:00+0800

还需要看下那个issue最终的解决方案是什么。

**Comment by new-xd** [comment]
看到最后也没看明白最终的解决方案是什么样的。
不过有提到Ruby2.2应该是对这个问题有一些修改。
而我这边由于是win7，所以是按照[非官方文档](http://jekyllrb.com/docs/windows/#installation)安装的ruby2.0。
估计ruby版本高于2.2的朋友应该没问题。

**Comment by new-xd** [comment]
使用[Chocolatey](https://davidburela.wordpress.com/2015/11/28/easily-install-jekyll-on-windows-with-3-command-prompt-entries-and-chocolatey/)重新安装了ruby jekyll
ruby版本 2.2.3p173  jekyll版本 3.0.1
本地博客时间还是不对，date的格式中还是需要添加时区信息
