### ISSUE TITLE
请问如果自己加发送邮件的功能的话有什么思路方法吗？

### ISSUE THREAD

**Issue by Wenhanz** [Huxpro/huxpro.github.io#255]
因为自己不太懂前端的技术，想问下如果自己加发送邮件的功能，需要做什么修改呢？

**Comment by kcdyx1** [comment]
发送邮件的功能？

**Comment by kcdyx1** [comment]
> > 发送邮件的功能？
> 
> 比如说增加一个信封的icon 点击可以直接向我发送邮件

可以啊，加个a标签，链接写成mailto:xxxx@xx.com，就可以了。或者在md文件里写[✉️](mailto:xxxx@xx.com)，也可以。

**Comment by Wenhanz** [comment]
> > > 发送邮件的功能？
> > 
> > 
> > 比如说增加一个信封的icon 点击可以直接向我发送邮件
> 
> 可以啊，加个a标签，链接写成mailto:[xxxx@xx.com](mailto:xxxx@xx.com)，就可以了。或者在md文件里写[✉️](mailto:xxxx@xx.com)，也可以。

神奇！谢谢！

**Comment by kcdyx1** [comment]
> > > > 发送邮件的功能？
> > > 
> > > 
> > > 比如说增加一个信封的icon 点击可以直接向我发送邮件
> > 
> > 
> > 可以啊，加个a标签，链接写成mailto:[xxxx@xx.com](mailto:xxxx@xx.com)，就可以了。或者在md文件里写[✉️](mailto:xxxx@xx.com)，也可以。
> 
> 神奇！谢谢！

客气了。。。md里要写成“[邮箱]（mailto:XXX@XXX.com）”，把双引号去了，括号换半角的

**Comment by Wenhanz** [comment]
> mailto:[xxxx@xx.com](mailto:xxxx@xx.com)

完美解决 我以为还要加个icon 没想到可以用emoji哈哈哈
