### ISSUE TITLE
代码段之代码和背景颜色对比不明显

### ISSUE THREAD

**Issue by xzchsia** [Huxpro/huxpro.github.io#260]
合并了最新的代码高亮和linenumber，使用\``` XXX \``` 这种形式的markdown发布了以后，文字和背景颜色对比不明显，是否可以修改下。
谢谢

可以查看这个看看对比的效果，
https://xzchsia.github.io/2018/08/29/androidstudio-offline-mode-gradle-junit-issue/

**Comment by Huxpro** [comment]
在三个撇号后面加上 java 试试？

**Comment by Huxpro** [comment]
不过默认颜色确实太暗了
Will fix

**Comment by Huxpro** [comment]
https://xzchsia.github.io/2018/09/05/java-lambda/
这一页就不错~
