### ISSUE TITLE
markdown语法文章标题前面多出#

### ISSUE THREAD

**Issue by jinglongjun** [Huxpro/huxpro.github.io#267]
MarkDown语法编写标题后，如

` ## 前言`

显示效果为#前言  请问这个要如何修复呢？

**Comment by jinglongjun** [comment]
具体可以 查看  https://jinglongjun.github.io/2018/10/14/MarkDown%E8%AF%AD%E6%B3%95%E6%B5%8B%E8%AF%95/

**Comment by nicolechen412** [comment]
_config里面，anchorjs: false

**Comment by jinglongjun** [comment]
好的，谢谢，设置后搞定
