### ISSUE TITLE
help!!!! npm install not work and hexo server can not run

### ISSUE THREAD

**Issue by Zirpon** [Huxpro/huxpro.github.io#276]
![image](https://user-images.githubusercontent.com/4457298/48658577-746f5680-ea7f-11e8-8391-1ad198d6973b.png)

![image](https://user-images.githubusercontent.com/4457298/48667517-ab427c80-eb12-11e8-8697-108ea7c73e91.png)

**Comment by Zirpon** [comment]
i don't know front end develop at all, please help~~~~~

**Comment by caiodomingues** [comment]
This should work, i think
```npm install --save-dev grunt```

**Comment by Zirpon** [comment]
> This should work, i think
> `npm install --save-dev grunt`

it seems throw exception

**Comment by Zirpon** [comment]
我是真的用不了啊
拉下来以后直接 npm install
hexo server 
服务器没启动

**Comment by Zirpon** [comment]
我觉得我要放弃了....

**Comment by Huxpro** [comment]
@Zirpon this repo is not a Hexo theme but Jekyll theme.
A Hexo them is ported and can be founded here: https://github.com/Kaijun/hexo-theme-huxblog

Best wishes.
