### ISSUE TITLE
怎么样去掉portfolio这个标签～～～～

### ISSUE THREAD

**Issue by HaoQChen** [Huxpro/huxpro.github.io#277]
如题

**Comment by HaoQChen** [comment]
直接删除文件夹即可～～～

**Comment by yanshigou** [comment]
> 直接删除文件夹即可~~~

3q

**Comment by HaoQChen** [comment]
> > 直接删除文件夹即可~~~
> 
> 3q

不谢不谢～～～～也可以关注一下我的github.io.嘻嘻

**Comment by nuistzhou** [comment]
直接删除portfolio只去掉了从Home的访问方式，如果点到别的Tab， 比如About 或者 Archive， 你就会发现Portfolio标签还在。
所以，继续求解决办法！

**Comment by ThitherShore** [comment]
一个更不暴力的做法是在 `_config.yml` 里exclude掉这个文件夹
```
exclude: ["portfolio", less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]```

**Comment by junqianghan** [comment]
portfolio/index.html 里面
hide-in-nav: true
