### ISSUE TITLE
Short About broken when description turn off but avatar on.

### ISSUE THREAD

**Issue by ebnbin** [Huxpro/huxpro.github.io#29]
In the side bar, there should be a spacing expected between avatar and SNS Link when description turned off.

**Comment by Huxpro** [comment]
@ebnbin HI, thanks for your reporting.

The bug is fixed. Please checkout [this commit](https://github.com/Huxpro/huxblog-boilerplate/commit/dec3ba97100b0d74dbae6f7391d800e464b504f6) and merging.
