### ISSUE TITLE
域名修改

### ISSUE THREAD

**Issue by skybjf** [Huxpro/huxpro.github.io#3]
打算采用你的这个模版
好像可以省好多事……

Jekyll的要求不是 http://username.github.io/projectname 么
求教：是怎么把域名改成你自己的呢

**Comment by skybjf** [comment]
没找到这个链接去哪里修改
比如：http://huangxuan.me/about/
真正被访问的文件应该是http://huangxuan.me/about.html这个才对···
是怎么做到···修改了路径的

**Comment by Huxpro** [comment]
域名这个，有个叫 CNAME 的文件，就是用来做这个事情的

链接那个其实你不用担心，Jekyll 的 URL 是动态化的，这个 html 本质也是模版文件，需要做一次渲染，生成静态化 html 再吐给浏览器的。也就是说，你在访问 about/ 时并没有真正访问  about.html ，不知道我说清楚了没有哈

**Comment by skybjf** [comment]
thx
我再琢磨琢磨哈~

**Comment by skybjf** [comment]
弱弱的问
是不是必须购买过一个域名才可以像你一样修改为自己的想要的域名

**Comment by Huxpro** [comment]
是的～

**Comment by hbxz** [comment]
你好。请问一下，我启用自定义域名后，可以显示出博客，但是是纯HTML，无其他样式，比如图片和字体等。
我的操作流程如下：
1 fork了你的博客repo
2 启用了github page
3 修改CNAME 文件为 `jasonlearning.info` 
4 在namesilo上增加Resource Records，第一项为 “	A	192.30.252.153”（该ip为namesilo上对github的默认ip，暂不怀疑有问题 ），第二项为“www	CNAME	hbxz.github.io”  第三项为 “blog	CNAME	hbxz.github.io”
最后：我可以访问 jasonlearning.info，但失去了样式。

另一个疑惑：
如果我修改3为“www.jasonlearning.info” 则访问时只有“hello world”，样式和内容是我之前租用的vps的页面。
ping www.jasonlearning.info 的IP 和 hbxz.github.io 相同，但结果却跑到了完全不同IP的vps上边去。。。这个现象我很不解。
不知道能否请你有空指点一下。十分感谢。
