### ISSUE TITLE
博客访问不了，求指点

### ISSUE THREAD

**Issue by wang-xiong** [Huxpro/huxpro.github.io#303]
Fastly error: unknown domain:xxx.top. Please check that this domain has been added to a service.

Details: cache-hnd18732-HND

**Comment by Android-KitKat** [comment]
https://help.github.com/en/articles/using-a-custom-domain-with-github-pages

在使用的域名下添加CNAME记录，值为`wang-xiong.github.io`。

**Comment by Android-KitKat** [comment]
> https://help.github.com/en/articles/using-a-custom-domain-with-github-pages
> 
> 在使用的域名下添加CNAME记录，值为`wang-xiong.github.io`。

似乎已经可以访问了，那没问题了。

**Comment by wang-xiong** [comment]
可以了，修改了下阿里云的dns解析好了

**Comment by Android-KitKat** [comment]
> 可以了，修改了下阿里云的dns解析好了

嗯，记得将Issues改为Close。
