### ISSUE TITLE
已看过首页依然有关于 "Page Build Warning"的email 的问题

### ISSUE THREAD

**Issue by twoheartliu** [Huxpro/huxpro.github.io#308]
邮箱原文：
The page build completed successfully, but returned the following warning for the `master` branch:

The custom domain for your GitHub Pages site is pointed at an outdated IP address. You must update your site's DNS records if you'd like it to be available via your custom domain. For more information, see https://help.github.com/en/articles/using-a-custom-domain-with-github-pages.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

------

确认修改了 CNAME 文件中的域名为自己的域名

------

在_config.yml文件中加上了gems: [jekyll-paginate].

其中有 highlighter: rouge 

------
解析管理如图所示：
![](http://ww1.sinaimg.cn/large/4871c945ly1g33j9014jdj214m09pmxp.jpg)

希望大佬不吝赐教

**Comment by Huxpro** [comment]
This looks nothing related to this theme but your DNS configurations.
