### ISSUE TITLE
header-img浅色图片导致文章标题看不清

### ISSUE THREAD

**Issue by Yanqi-Chen** [Huxpro/huxpro.github.io#312]
请问header-img为浅色图片时，希望文章标题颜色是深色而非白色，否则会看不清（header-img-credit也看不清）能否进行设置，或者如何修改模板？

**Comment by linziwei1** [comment]
给你的浅色图片加一个25%左右透明度的黑色遮罩层

**Comment by Yanqi-Chen** [comment]
@linziwei1 感谢，发现作者在YAML Front Matter中预留了参数header-mask设置遮罩透明度

**Comment by Huxpro** [comment]
是的 ;)

**Comment by MessiahChen** [comment]
> @linziwei1 感谢，发现作者在YAML Front Matter中预留了参数header-mask设置遮罩透明度

请问这个有哪些参数在哪个文件里面看呀？
