### ISSUE TITLE
markdown中不支持简书的图片链接

### ISSUE THREAD

**Issue by CoderLeonidas** [Huxpro/huxpro.github.io#323]
嗨，作者您好！我想把我简书上的文章迁移过来，但是发现原先简书上的图片，在你的模板中不能显示，而在一些markdown编辑器如MacDown中，是可以正常显示的，这个有办法解决吗？因为简书文章中的图片大多用的是简书的图床，所以全部替换成其他图床，工作量很大呢

**Comment by Huxpro** [comment]
这应该跟博客主题无关，我估计是简书的图床服务器不接受非简书以及 localhost 的域名导致的。能打开开发者工具看一下报错吗？

**Comment by Accelerator086** [comment]
> 这应该跟博客主题无关，我估计是简书的图床服务器不接受非简书以及 localhost 的域名导致的。能打开开发者工具看一下报错吗？

@CoderLeonidas @Huxpro 
简书做了防盗链，其他域名引用他的图片就 403 访问拒绝了：  
![image](https://user-images.githubusercontent.com/32789300/78909627-67109d00-7ab6-11ea-83bf-e7c7ca142881.png)  
Reference: [https://hacpai.com/article/1477644246931](https://hacpai.com/article/1477644246931)  
我之前用简书的文章直接上传，结果不行，只好一点一点弄
