### ISSUE TITLE
关于header-img的图片存放路径问题

### ISSUE THREAD

**Issue by hacker-jerry** [Huxpro/huxpro.github.io#328]
作者您好，我想问一下为何在header-img后的图片路径必须是上传在github中的相对路径才能在渲染的时候找到？
我想用外链替代，这个想法可行吗？如果可以，应该如何设置呢？谢谢！

**Comment by wq133** [comment]
你好，请问您是怎么解决的。
看了issue40，看提示，修改了/includes/intro-header.html中的header.intro-header{中的background-image: ubrl(，但是在博文中添加如下，header-img: "https://gitee.com/wqh133/blog_img/raw/master/HD_1.jpg"
本地服务器运行之后，博文进去后并没有成功加载背景图，请问还需要修改什么css文件呢。
