### ISSUE TITLE
请问data-thread-id是什么ID？如何获取？

### ISSUE THREAD

**Issue by lianghuiyuan** [Huxpro/huxpro.github.io#33]
请问一下的data-thread-id="1187623191091085319"是什么ID，从哪里获取的ID？ 谢谢！
``` javascript
<!-- 多说评论框 start -->
<div class="comment">
    <div class="ds-thread"
    {% if site.duoshuo_username == "Huxpro" %}
        data-thread-id="1187623191091085319"
    {% else %}
        data-thread-key="{{site.duoshuo_username}}/about"
    {% endif %}

    data-title="{{page.title}}"
    data-url="{{site.url}}/about/"></div>
</div>
<!-- 多说评论框 end -->

**Comment by BruceZhaoR** [comment]
这是官方说明文档：
```html
<!-- 多说评论框 start -->
     <div class="ds-thread" 
        data-thread-key="请将此处替换成文章在你的站点中的ID" 
        data-title="请替换成文章的标题" 
        data-url="请替换成文章的网址">
     </div>
<!-- 多说评论框 end -->
```
我的做法如下,另外还增加了一个热评文章链接：
```html
 {% if site.duoshuo_username %}
 <!-- 多说评论框 start -->
 <div class="comment">
        <div class="ds-thread"
               data-thread-key="{{page.id}}"
               data-title="{{page.title}}"
               data-url="{{site.url}}{{site.BASE_PATH}}{{page.url}}" >
         </div>
                <!-- 多说热评文章 end -->
		<div class="ds-top-threads" data-range="monthly" data-num-items="5"></div>
   </div>
<!-- 多说评论框 end -->
 {% endif %}
```
注意：我这里的 `site.BASE_PATH` 是自己的定义的变量，等同于模板里面的`site.baseurl`.

关于 data-thread-key 看这里解释 http://dev.duoshuo.com/docs/5003ecd94cab3e7250000008
关于 page.id 看这里：http://jekyllcn.com/docs/variables/
于是的每篇文章的thread-key都不会相同，方便了以后评论迁移及管理。
你可以可以参考我的blog 欢迎评论测试。<http://brucezhaor.github.io>

下面是多说后台管理，我理解的thread-key就是每篇文章的唯一标识，不知道时候正确，还请高人指正。

![data-thread-key](https://cloud.githubusercontent.com/assets/8092534/12446234/e01e3f72-bfa3-11e5-9152-493cc4d32026.png)

希望能够帮助你。:smile:

**Comment by lianghuiyuan** [comment]
@BruceZhaoR  如问题中描述的，data-thread-id="1187623191091085319"这个data-thread-id是什么ID呢，如何获取？

**Comment by Huxpro** [comment]
@lianghuiyuan  

由于当时多说数据库迁移的问题，我的评论有部分丢失，所以使用 id 强行索引回来的。
你并不需要使用这个 id，正常情况下，使用 key 就可以与其它文章区分了

关于 `data-thread-key`， 具体可以参见 @BruceZhaoR 的回答～（感谢 @BruceZhaoR ）

**Comment by BruceZhaoR** [comment]
请仔细你看我的回答和下面的 多说 官方链接-关于thread-key的。反正我的方法是能用的，Hux的ID我也不清楚怎么来的，你可以发邮件问他。


From BruceZhao's iPhone.
在2016年01月21日 21:52，Mr.L 写道:

@BruceZhaoR 如问题中描述的，data-thread-id="1187623191091085319"这个data-thread-id是什么ID呢，如何获取？

**Comment by lianghuiyuan** [comment]
Ok, 明白了，非常感谢两位解答。 @BruceZhaoR  @Huxpro
