### ISSUE TITLE
最近用博客写些Vue的笔记,如果出现{{msg}} 文章就会显示空白,尝试\转义也不行

### ISSUE THREAD

**Issue by Ivens-Zhang** [Huxpro/huxpro.github.io#335]
![image](https://user-images.githubusercontent.com/49118158/69606735-96ba8d80-105e-11ea-9c41-dace4aa2aa6b.png)

![image](https://user-images.githubusercontent.com/49118158/69606766-ab972100-105e-11ea-8413-b593bab10de7.png)

**Comment by Ivens-Zhang** [comment]
不光是{{msg}}会出现这种问题,只要是两个大括号都会这样

**Comment by Ivens-Zhang** [comment]
如果谁有解决办法,希望不吝赐教,谢谢

**Comment by Huxpro** [comment]
Unfortunately, that's an issue of Jekyll.
You might have to wrap them with raw tags.
See https://github.com/jekyll/jekyll/issues/6217
