### ISSUE TITLE
大佬，求指导，乱码怎么办

### ISSUE THREAD

**Issue by disxo** [Huxpro/huxpro.github.io#340]
![image](https://user-images.githubusercontent.com/20137434/71949302-f84d4a80-320d-11ea-9acd-654b7c5935d7.png)

**Comment by jinchangzhi** [comment]
我在github上fork了，可以正常显示，到gitee上，和你显示的和上面一样

**Comment by SwetyCore** [comment]
> 我在github上fork了，可以正常显示，提交到gitee上，就显示的和上面一样
需要更改_config.yml相应的内容

**Comment by disxo** [comment]
不尝试了，忘记这个问题了
