### ISSUE TITLE
SNS settings username填了，直接访问网站没有社交图标，但是jekyll serve有

### ISSUE THREAD

**Issue by realburt41** [Huxpro/huxpro.github.io#347]
jekyll serve启动
![1](https://user-images.githubusercontent.com/34377344/74844252-28891c80-5368-11ea-86d8-dce43908e2af.png)
直接访问
![2](https://user-images.githubusercontent.com/34377344/74844264-2b840d00-5368-11ea-928b-9933ba828a24.png)

**Comment by realburt41** [comment]
解决了，谢谢大佬
https://github.com/Huxpro/huxblog-boilerplate/issues/17

**Comment by Lanzhou-J** [comment]
解决方法：
将相关文件里（`head.html`）的：
`<link href="http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">`
全部更换为：
`<link href="https://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">`
