### ISSUE TITLE
目录只占满 article

### ISSUE THREAD

**Issue by Ynjxsjmh** [Huxpro/huxpro.github.io#349]
现在的目录会扩展到 footer，请问如何让它只在 article 里，就像 [SO](https://stackoverflow.com/) 那样

![image](https://user-images.githubusercontent.com/40143136/75711239-021c9700-5d01-11ea-976e-6cf12c600a3e.png)

更多问题详情参考下面这个：

https://www.reddit.com/r/bootstrap/comments/fcaip9/catalog_in_row_expan_into_another_row_in/

**Comment by Ynjxsjmh** [comment]
看上去你是用 https://github.com/davist11/jQuery-One-Page-Nav 这个 repo 来实现 toc 高亮当前小节的，不知道这个对 toc 跨 row 有没有什么影响。

**Comment by roife** [comment]
在 `hux-blog.js` 下面的这一段

```js
                $catalog.show()
                if (currentTop > (bannerHeight + 41)) {
                    $catalog.addClass('fixed')
                } else {
                    $catalog.removeClass('fixed')
                }
```

下面添加这个：

```js
                var endPos = $('#article-end-anchor').offset().top;
                var catalogBodyHeight = $('.catalog-body').height();
                if (endPos < currentTop - 21 + catalogBodyHeight + 716 - 570) {
                    $catalog.offset({ top: endPos - catalogBodyHeight - 716 + 570 });
                } else {
                    $catalog.css("top", "");
                }
```

然后记得生成 `hux-blog.min.js`

**Comment by Ynjxsjmh** [comment]
谢谢，我回忆了下，这个问题我貌似是抄了抄 https://github.com/olOwOlo/hugo-theme-even 这里目录的实现方式给解决了。
