### ISSUE TITLE
没有域名如何访问呢

### ISSUE THREAD

**Issue by zhaogituser** [Huxpro/huxpro.github.io#352]
CNAME 文件为空不行啊

**Comment by DotIN13** [comment]
没有域名，可以直接使用githubid.github.io作为域名  
在repo的Setting - Static Page进行设置  
CNAME文件删除即可

**Comment by zhaogituser** [comment]
> 没有域名，可以直接使用githubid.github.io作为域名
> 在repo的Setting - Static Page进行设置
> CNAME文件删除即可
谢谢已经正常，我之前手动删除CNAME文件不行。我之后在setting里点击了保存自动删除就行了
