### ISSUE TITLE
如何设置navbar中某部分不显示？

### ISSUE THREAD

**Issue by Accelerator086** [Huxpro/huxpro.github.io#357]
例如对于 [Hux Blog](https://huangxuan.me) ，我想隐藏about这一标签，但是访问[Hux Blog - About](https://huangxuan.me/about) 时也能够打开，该怎么操作呢？

**Comment by DotIN13** [comment]
如果只是要在顶部navbar隐藏about的话，只需要在`/about.html`的顶部YAML front matter添加一行
```yaml
hide-in-nav: true
```
就阔以了。

**Comment by Accelerator086** [comment]
> 如果只是要在顶部navbar隐藏about的话，只需要在`/about.html`的顶部YAML front matter添加一行
> 
> ```yaml
> hide-in-nav: true
> ```
> 
> 就阔以了。

我试了一下，还是不行，请问这个 `hide-in-nav` 参数是在 `.\_includes\nav.html` 中实现的么？

**Comment by DotIN13** [comment]
> > 如果只是要在顶部navbar隐藏about的话，只需要在`/about.html`的顶部YAML front matter添加一行
> > ```yaml
> > hide-in-nav: true
> > ```
> > 
> > 
> > 就阔以了。
> 
> @DotIN13 我试了一下，还是不行，请问这个 `hide-in-nav` 参数是在 `.\_includes\nav.html` 中实现的么？

对的，nav.html第27行

```html
{% for page in site.pages %}
{% if page.title and page.hide-in-nav != true %}
<li>
    <a href="{{ page.url | prepend: site.baseurl }}">{{ page.title }}</a>
</li>
{% endif %}
{% endfor %}
```

hux把这个if判断写在了nav.html里，如果页面的hide-in-nav值为true就不会添加到顶部navbar。

如果你的nav.html中没有可以添加这一语句。

**Comment by Accelerator086** [comment]
> > > 如果只是要在顶部navbar隐藏about的话，只需要在`/about.html`的顶部YAML front matter添加一行
> > > ```yaml
> > > hide-in-nav: true
> > > ```
> > > 
> > > 
> > > 就阔以了。
> > 
> > 
> > @DotIN13 我试了一下，还是不行，请问这个 `hide-in-nav` 参数是在 `.\_includes\nav.html` 中实现的么？
> 
> 对的，nav.html第27行
> 
> ```
> {% for page in site.pages %}
> {% if page.title and page.hide-in-nav != true %}
> <li>
>     <a href="{{ page.url | prepend: site.baseurl }}">{{ page.title }}</a>
> </li>
> {% endif %}
> {% endfor %}
> ```
> 
> hux把这个if判断写在了nav.html里，如果页面的hide-in-nav值为true就不会添加到顶部navbar。
> 
> 如果你的nav.html中没有可以添加这一语句。

是这样的，试验成功了，我少了if后面的 `page.hide-in-nav != true` 判断，谢谢你！
