### ISSUE TITLE
移植模板时自己出了些小问题，求指教

### ISSUE THREAD

**Issue by SilverBulletZyp** [Huxpro/huxpro.github.io#36]
很喜欢你做的模板，移植到自己的仓库时不知道操作了什么页面出现了些小问题，由于不懂前端代码，截了几张图片
![qq20160128-0 2x](https://cloud.githubusercontent.com/assets/12904640/12635628/5378f968-c5c0-11e5-92eb-971a3e487d93.png)
![qq20160128-1 2x](https://cloud.githubusercontent.com/assets/12904640/12635629/537bc22e-c5c0-11e5-8de3-02fcf4b96e84.png)

，恳请指教下怎么修改呢？
1、博客正文页右边多出了一列滚动条
2、使用多说和disqus时页面布局紊乱了

**Comment by SilverBulletZyp** [comment]
我重新移植了一遍模板，滚动条问题可以消失，但是分享部分一直是排版混乱的，我clone了你的稳定版和更新版，在本地jekyll serve了一下两个仓库发现都有这个问题，想请问下是什么原因呢，或者实在不行的话能不能去掉评论部分？

**Comment by BruceZhaoR** [comment]
请仔细阅读 README-zh.md. 如果实在无法解决再来提问。

**Comment by Huxpro** [comment]
@SilverBulletZyp  多说有域名白名单，所以在本地时并不会加载。自己注册多说或者 Disqus 的帐号即可。详情可以参见 README 或 README.zh 的相关部分

**Comment by SilverBulletZyp** [comment]
@Huxpro 好的，非常感谢！
