### ISSUE TITLE
Chrome Extension Application

### ISSUE THREAD

**Issue by MessiahChen** [Huxpro/huxpro.github.io#376]
Chrome会检测出Chrome Extension Application，有地方让它不显示吗
![image](https://user-images.githubusercontent.com/39381989/88359208-6ae5d800-cda4-11ea-9f88-3ebc6ffe65fb.png)

**Comment by DotIN13** [comment]
Hux made this theme a Progressive Web Application so it's more of intentional. If you don't like it, I assume you could manually remove the manifest and service worker javascript files.

**Comment by MessiahChen** [comment]
> Hux made this theme a Progressive Web Application so it's more of intentional. If you don't like it, I assume you could manually remove the manifest and service worker javascript files.

Hi, I commented out the codes below in _includes/head.html and it works. Thank you for your suggestion！
```
<!-- Web App Manifest -->
<!--    <link rel="manifest" href="{{ site.baseurl }}/pwa/manifest.json">-->
```
