### ISSUE TITLE
页面底端Facebook无法显示

### ISSUE THREAD

**Issue by voleking** [Huxpro/huxpro.github.io#38]
<img width="419" alt="screen shot 2016-01-30 at 19 13 11" src="https://cloud.githubusercontent.com/assets/13161779/12695341/f7b30a20-c785-11e5-9e0e-0eba9b9ea775.png">

**Comment by Huxpro** [comment]
@voleking 
Hey, I check <http://voleking.github.io/>, and everything seems to be all right.
Did you fixed it yourself?

**Comment by voleking** [comment]
@Huxpro 
Well, I find this issue only happen on my mac.
My mac version is 10.11.1.
Neither chrome nor safari can make a different.
I find everything well on my android phone.
hope help :)

**Comment by BruceZhaoR** [comment]
建议使用 font-awesome这个css里面自带图标，我看这个模板的头文件里面加载了 font-awesome的cdn
```html
<link href="http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
```

只不过是4.2，最新版本是4.5。既然有了，为何不直接使用呢？目前除了知乎图标外，其他的图标都是有的，当然你也可以去提交要求加上知乎的图标。请参考这个网址：http://fontawesome.io/icon/facebook/    weibo的图标： http://fontawesome.io/icon/weibo/   看examples  然后搜索相应的链接。

或者访问我的blog： http://brucezhaor.github.io  在鄙人的头像下面你审查一下源代码就知道具体的用法了。

抱歉没有使用英文，因为鄙人英文水平不好，用中文表达最快~  :sorry:

**Comment by voleking** [comment]
@BruceZhaoR 
I know what you mean,and I try to use v4.5 too,But nothing help.
My problem only happen on my mac. When I visit my blog the first time, then Facebook icon appears currently. However, If I refresh it or go to another page, the "F" disappears like what the picture reveals.
I think it may something wrong with my own computer.

Anyway,Thx.

By the way, my English is poor too.But I subscribe to the view that you cannot improve your English unless use it.

**Comment by BruceZhaoR** [comment]
@voleking  Maybe, you can open my website http://brucezhaor.github.io  in your Mac to test if the Font-awesome works well.

**Comment by Huxpro** [comment]
@voleking I thought you can check the DOM nodes and HTTP requests in your Chrome Devtools, which always help. Since this is some of your local problem, Im sorry that I could not help more.

@voleking @BruceZhaoR you guys are cute ;)  And I'm ready to close this issue.
