### ISSUE TITLE
。。。

### ISSUE THREAD

**Issue by striverx** [Huxpro/huxpro.github.io#4]

**Comment by Huxpro** [comment]
Well...can not really tell..

尽管可能有很多误用，但还是 keep read/use/write it 吧～
程序员的话，可以先从读文档开始做起，慢慢看一些国外的东西(Quora, Medium, Twitter) 什么的，慢慢就会好起来啦

**Comment by striverx** [comment]
好的，谢谢指点。

**Comment by MessiahChen** [comment]
nice question
