### ISSUE TITLE
页面宽度调整

### ISSUE THREAD

**Issue by bobcatzoo** [Huxpro/huxpro.github.io#404]
请问如何调整页面宽度,因为经常写LaTeX,如果页面宽度太窄的话,有些长公式显示就和右面目录重叠了,而且也会增加代码左右滑动的几率.

**Comment by YEY11** [comment]
可以在 MathJax 的 config 里添加 zoom 选项添加滑动功能：
MathZoom: {styles: {"#MathJax_Zoom": {overflow: "auto ! important"}}}

**Comment by xhql** [comment]
请问解决了？
