### ISSUE TITLE
markdown图片路径是新浪相册路径时无法正常显示

### ISSUE THREAD

**Issue by youthred** [Huxpro/huxpro.github.io#433]
比如这个路径 https://wx2.sinaimg.cn/large/005Ii7rngy1gocvh43u8ij30fx0a4jrg.jpg
![https://wx2.sinaimg.cn/large/005Ii7rngy1gocvh43u8ij30fx0a4jrg.jpg](https://wx2.sinaimg.cn/large/005Ii7rngy1gocvh43u8ij30fx0a4jrg.jpg)

在仓库里直接看md正常显示图片，但在hux blog中无法显示

**Comment by Huxpro** [comment]
新浪可能会检查 HTTP 请求来源

**Comment by yizibi** [comment]
> 

七牛也不行了，最新的我试了github自己的，是可以的
