### ISSUE TITLE
文章生成目录的H1、H2级标题缩进不对

### ISSUE THREAD

**Issue by Kannmu** [Huxpro/huxpro.github.io#455]
发现./css/hux-blog.min.css中，关于自动生成的侧边目录栏缩进参数格式有问题：
以二级标题为例，源文件中书写如下：
`side-catalog .catalog-body .h2_nav{margin: left 8px ;; font-size:13px;font-weight:650}`
而正确的格式应该为：
`side-catalog .catalog-body .h2_nav{margin-left: 8px ; font-size:13px;font-weight:650}`
**出现了margin-left的传参格式错误，同时多了一个分号。**
而后面的H3、4、5、6级标题未见错误。
修改后的H1、2级标题如下：
`side-catalog .catalog-body .h1_nav{margin-left: 0px;font-size:14px;font-weight:700}.side-catalog .catalog-body .h2_nav{margin-left: 8px;font-size:13px;font-weight:650}.`

更新后生成的目录缩进正常了
![tmp4963](https://github.com/Huxpro/huxpro.github.io/assets/53987473/2e982740-a325-4b81-a381-8ec47c6e46cc)

**Comment by shake** [comment]
等待修复。

**Comment by shake** [comment]
我尝试修改，H5，H6，不生效，其实是够用了。
https://github.com/shake/shake.github.io/blob/master/css/hux-blog.min.css
这是我的css，如果方便，share一下。

**Comment by shake** [comment]
https://github.com/Kannmu/Kannmu.github.io/blob/master/css/hux-blog.min.css

测试一下，完全没问题。https://chenshake.com/2023/10/21/side-catalog-test/

**Comment by ahan-ai** [comment]
Got the same problem, can it be fixed？

**Comment by Kannmu** [comment]
> Got the same problem, can it be fixed？

my solution is changing the code  `side-catalog .catalog-body .h2_nav{margin: left 8px ;; font-size:13px;font-weight:650}`
in file `./css/hux-blog.min.css` into `side-catalog .catalog-body .h2_nav{margin-left: 8px ; font-size:13px;font-weight:650}`

because of the replication of semicolons

**Comment by ahan-ai** [comment]
> https://github.com/Kannmu/Kannmu.github.io/blob/master/css/hux-blog.min.css

this works, ths
