### ISSUE TITLE
多说评论框和分享如何使用？

### ISSUE THREAD

**Issue by rorschach** [Huxpro/huxpro.github.io#46]
我已经有了多说的模板代码，应该在哪些文件中使用呢？

**Comment by voleking** [comment]
在_layout中模板加

**Comment by rorschach** [comment]
@voleking　我想要添加文章后的评论框，是不是在post.html里添加？

**Comment by Huxpro** [comment]
@rorschach please read the [document](https://github.com/Huxpro/huxpro.github.io#comment):

> you can easily complete your comment configuration by just adding your short name into _config.yml:

```
duoshuo_username: _your_duoshuo_short_name_
# OR
disqus_username: _your_disqus_short_name_
```

**Comment by rorschach** [comment]
@Huxpro 搞定了，谢谢，你的模板很漂亮:)

**Comment by Huxpro** [comment]
@rorschach thanks for your nice word and Im ready to close this issue ;)
