### ISSUE TITLE
博客不显示

### ISSUE THREAD

**Issue by candycat1992** [Huxpro/huxpro.github.io#47]
首先感谢提供了这么漂亮的模板！

我今天使用这个写了一篇博客，但不知为什么它既没有显示在首页，也没有在Tags下，见https://github.com/candycat1992/candycat1992.github.io。

我对前端不熟悉，这是什么原因造成的呢？

**Comment by BruceZhaoR** [comment]
@candycat1992  看到你用的是模板，hux没有更新，pygments的高亮不再支持，使用rouge。建议参考 huxpro.github.io 的 _yaml 进行设置。

或者去我fork的仓库，重新copy一下我稍微修改的[模板](https://github.com/BruceZhaoR/huxblog-boilerplate) ， 预览效果在[这里](http://brucezhaor.github.io/huxblog-boilerplate/) 。

**Comment by candycat1992** [comment]
@BruceZhaoR 谢谢你的回答！不过我改过_yaml，但是还是一样，在本地和部署到github上都还是没有任何文章显示出来。

**Comment by BruceZhaoR** [comment]
你可以试试第二个方案，刚我也看了你的repository，一时也没找出来原因，不过我觉得问题应该出在 layout 跟 index。


我还是建议不要把时间浪费在这个上面 重新fork模板然后修改。

**Comment by candycat1992** [comment]
@BruceZhaoR 最后终于显示出来了，但是我也不知道为什么。我把博客日期中的小时去掉了：
把date:       2016-03-02  12:00:00改成了date:       2016-03-02，就能显示出来了，好奇怪……

关键是，我把模板下下来的时候都是好的，他的日期也是这么写的，我就改了下年月日，但自带的博客都是可以显示出来，我新加的这篇始终显示不出来！

还有个问题，就是Featured Tags，我看文档里说那些size大于设置的tag就会显示在边栏，什么是tag的size呢？比如：
---
layout:     post
title:      "我的独立博客"
subtitle:   "第一篇"
date:       2016-03-02
author:     "Candycat"
header-img: "img/post-bg-2015.jpg"
tags:
    - 闲谈
---

闲谈就是我新加的一个tag，它的size是什么？怎么才会显示在首页的侧栏？

**Comment by BruceZhaoR** [comment]
@candycat1992  
关于date的写法，[Jekyll文档](http://jekyllcn.com/docs/frontmatter/#section-2)，说是可以的。为何显示不了我也不知道了, 需要请 @Huxpro 或者专业人士来解答。

size 为该标签下的文章数，具体看Hux翻译的这篇[中文文档](https://github.com/Huxpro/huxpro.github.io/blob/master/README.zh.md#featured-tags)

**Comment by candycat1992** [comment]
@BruceZhaoR Ok！明白了，多谢！

**Comment by Huxpro** [comment]
@candycat1992  Hey，“在我这边是好的”，虽然我不想这么说，但是这个问题可能无法验证 ;)
关于 size，如[相关文档](https://github.com/Huxpro/huxpro.github.io/blob/master/README.zh.md#featured-tags) 中所述，改成 0 就可以显示在侧边栏上啦。

感谢 @BruceZhaoR 帮助，这个应该跟 pygments 高亮无关哈，不过确实要更新下 boilerplate 了 OTZ

Closed if no more issue. Thx guys

**Comment by candycat1992** [comment]
@Huxpro 恩我今天也试了一下的确重现不出来了……但之前提问的时候的确是这个情况，就改了个日期就好了。

模板的确要更新了，比如head.html里面就由于<link rel="shortcut icon" href="img/favicon.ico">图片路径有些问题会导致一些页面显示不出来网站的图标。最后谢谢分享！

**Comment by Huxpro** [comment]
@candycat1992 @BruceZhaoR 

Jekyll 默认时间是格林尼治时间，或者说是 GMT 时间(Greenwich Mean Time，格林尼治平时)，然后生成的时候又会本地化一次变成UTC(Universal Time Coordinated，协调世界时)。

因此如果文件的 YAML头部信息里的date时间精确到秒的话，那么最后使用page.date|date %d时日期就有可能变化，比如9月3日17点就会变成9月4日1点。。。

解决方案是在_config.yal里加上这样一行

```
timezone: CN
```

信息来源：<http://mickir.xyz/blog/2015/09/Timezone-in-Jekyll.html>
