### ISSUE TITLE
请教下博主类似于你博客中的portfolio页面如何设置生成？？

### ISSUE THREAD

**Issue by Rogero0o** [Huxpro/huxpro.github.io#49]
如题

**Comment by Huxpro** [comment]
Emm..The core part is just a static page and nothing fancy, which you can easily figure out in the code directly. 

It is not generated by a liquid template, which is wanted maybe. But not done yet. That's why boilerplate not include portfolio page currently.

Hux

**Comment by Rogero0o** [comment]
Roger that , thanks.
