### ISSUE TITLE
Markdown语法解析问题

### ISSUE THREAD

**Issue by diyselfway** [Huxpro/huxpro.github.io#5]
你好，很喜欢你制作的博客模版，最近在折腾[我的博客](http://diyselfway.github.io)，Fork了你的项目。可是在提交博文的时候，发现Markdown解析有点问题，会在标题旁多个#号，二级三级目录无法解析，表格分割线无法解析，如下：
![image](https://cloud.githubusercontent.com/assets/6139337/9829980/3e679e58-5950-11e5-927a-14958ec5ce05.jpg)
![image](https://cloud.githubusercontent.com/assets/6139337/9830128/ed01af36-5954-11e5-8a9c-eb4a7fb3d7d1.jpg)

我查看了你的博客，以及其他fork自你博客的朋友的博客，发现都存在这个问题(win、ios及Android下都存在)。我在本地用Jekyll调试也出现了这一问题，由于我在Github上预览post时发现解析正常，所以我尝试注释掉config里面的markdown：kramdown，问题依然存在。没办法了，只能来请教你了（中度强迫症患者，对页面的瑕疵不能忍，望解救）。

**Comment by Huxpro** [comment]
Hi, 

会在标题旁多个 # 号，是因为在 `post.html` 中调用了 [anchor.js](http://bryanbraun.github.io/anchorjs/)，目的是给每个标题增加一个“可以点击的锚点”，用以在分享时可以直接跳转到某个标题。
如果需要，我可以增加一个是否开启 anchor.js 的配置。如果你需要自定义，anchor.js 也提供了很多配置项，可以去文档查。

至于 Markdown 的解析问题，目前使用的是 Github Flavored Markdown，请自行确认语法是否 illegal

Thanks for your feedback!

**Comment by diyselfway** [comment]
谢谢，已经解决。
