### ISSUE TITLE
sidebar 的标题链接无法正确跳转

### ISSUE THREAD

**Issue by weehowe-z** [Huxpro/huxpro.github.io#50]
sidebar 当中的 `ABOUT ME`, `FEATURED TAGS` 的链接点击之后跳转到的是首页.

看代码大概是想转到对应的页面的
```html
<h5><a href="{{/tags/ | prepend: site.baseurl }}">FEATURED TAGS</a></h5>
```
可能漏了引号
```html
<h5><a href="{{ "/tags/" | prepend: site.baseurl }}">FEATURED TAGS</a></h5>
```

**Comment by Huxpro** [comment]
@weehowe-z  Thx! Fixed in <https://github.com/Huxpro/huxpro.github.io/commit/967ae376a16bdf3fd7e0eb930e3f7032d6e3add1>

**Comment by Huxpro** [comment]
居然有智能 close .... 叼叼叼……
