### ISSUE TITLE
It's always loading

### ISSUE THREAD

**Issue by terrytangyuan** [Huxpro/huxpro.github.io#51]
Looks like the web page is always loading. Anyone had this issue too?

**Comment by Huxpro** [comment]
@terrytangyuan Im convinced that no one has...
So, tell me what you encounter

**Comment by terrytangyuan** [comment]
It seems like the loading bar has been loading there for a very long time even though the page looks like already completed loading. BTW, I am in the US. Maybe there's some API service thats slow here?

**Comment by Huxpro** [comment]
@terrytangyuan yep, it is possible. You can use the Network panel in Chrome devtool to detect slow requests.

**Comment by terrytangyuan** [comment]
Thanks. Fixed! It's Baidu analytics. :-)
