### ISSUE TITLE
footer里的github页怎样生成？

### ISSUE THREAD

**Issue by wangpengfei15975** [Huxpro/huxpro.github.io#52]
rt

**Comment by BruceZhaoR** [comment]
@wangpengfei15975  请见 _includes 文件夹下的 footer.html 里面的76行的 <iframe>...</iframe>
https://github.com/Huxpro/huxpro.github.io/blob/master/_includes/footer.html#L76

**Comment by Shawkaine** [comment]
我的footer的图标本地预览没问题，放到github就没有图标了，见[shawkaine blog](https://shawkaine.github.io)，请教一下是怎么回事呢
