### ISSUE TITLE
按照步骤操作，还是收到Page build warning邮件

### ISSUE THREAD

**Issue by niushu** [Huxpro/huxpro.github.io#53]
jekyll 已经是3.1.2
也按照说明文档更新，配置了。
求助

**Comment by BruceZhaoR** [comment]
warning 的信息如果能贴出来或许大家可以帮你看看~  :blush:

**Comment by Huxpro** [comment]
@niushu  是的，麻烦贴出来 warning 的内容～

**Comment by voleking** [comment]
本地 >jekyll serve 预览出现的？

**Comment by niushu** [comment]
`The page build completed successfully, but returned the following warning:

CNAME already taken: example.com. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken for more information.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.`

**Comment by LucasIcarus** [comment]
@niushu  如果我没有猜错应该是CNAME 设置的问题吧。。 你得改成自己的域名？

**Comment by Huxpro** [comment]
@niushu  
噗……看来我得在文档里补充一下了；
Huxblog-Boilerplate 的 CNAME 文件里写的是 example.com；就是说如果你有自己的域名的话，你可以替换成自己的；
如果没有的话，可以设为空或者删除掉就好了

**Comment by voleking** [comment]
哈哈，还好我之前已经弄过一个简单的再 fork 的，顺利很多

**Comment by niushu** [comment]
@Huxpro 抱歉，之前看的报错跟jekyll版本有关。
后面收到标题一样的邮件，没留意内容了

**Comment by saisaitian** [comment]
我也出现这个问题，不知怎么解决
