### ISSUE TITLE
请教博主为何标题前面会有一个 “#” ？如何去除 或者 隐藏 ？？

### ISSUE THREAD

**Issue by Rogero0o** [Huxpro/huxpro.github.io#54]
使用 "##" 或者 “===========” 标题前面都会有个“#”，定位用的 ，要怎么去除呢？

**Comment by BruceZhaoR** [comment]
yaml 文件中  anchor = false
  
From BruceZhao's iPhone.

**Comment by BruceZhaoR** [comment]
这个其实是调用了一个anchor.js，可以设置形状，位置，是否隐藏 ... 等，具体去github上面看看设置指南。


From BruceZhao's iPhone.

**Comment by Rogero0o** [comment]
解决了， thanks , have a good day

**Comment by BruceZhaoR** [comment]
:blush:

**Comment by maoruibin** [comment]
@BruceZhaoR

> yaml 文件中  anchor = false

这个文件具体在什么位置，没有找到啊。

**Comment by xuepro** [comment]
到底是怎么弄的? 没说清楚啊
