### ISSUE TITLE
How to configure the site subtitle？

### ISSUE THREAD

**Issue by ArtinHuang** [Huxpro/huxpro.github.io#59]
just like the` Boilerplate of Hux Blog`, i could not found the edit extrance...

post a img like this:

![image](https://cloud.githubusercontent.com/assets/14356434/14061020/4d14ea32-f3b0-11e5-9777-9c410c7702d6.png)

**Comment by Huxpro** [comment]
@ArtinHuang 

Open `index.html`, you would see:
```
---
layout: page
description: "Boilerplate of Hux Blog"
---
```

All the subtitle of pages, of similarity to posts, can be modified in the front-matter of the corresponding files. Sorry for that documentation omission ;)
