### ISSUE TITLE
请问怎么才能做出你那样的背景图片效果？

### ISSUE THREAD

**Issue by JayWii** [Huxpro/huxpro.github.io#6]
如题，很喜欢博主的背景大图色调，想请教一下怎么才能调整出那样的效果？

**Comment by qingxiang-jia** [comment]
不请自来，我fork了HUX的repo，换用了另外一种风格的大图：http://qingxiang-jia.github.io/

**Comment by Huxpro** [comment]
@JayWii  
Well..It's actually a design issue. 

简单的来说：

- 图要好看
- 需要加一定的黑色遮罩使照片颜色变暗，和白色文字产生对比

你可以使用 PS，也可以用 CSS。
但是考虑到每张照片需要被处理的程度可能完全不同，所以我并没有硬编码一个黑色遮罩上去。

也正因如此， @qingxiang-jia  这样的自定义使用也变得更加可能，并且效果也很棒

Thanks to this issue.
I add [related content](https://github.com/Huxpro/huxpro.github.io#header-image) to the README.

**Comment by JayWii** [comment]
@Huxpro
谢谢指点～我决定还是用Ps来处理～
也谢谢 @qingxiang-jia 提供的参考，你的处理效果也非常nice，只是我个人更喜欢使用照片～～

**Comment by Huxpro** [comment]
@JayWii  GJ, so i gonna to close this issue, thx <3

**Comment by qingxiang-jia** [comment]
@Huxpro 谢谢指点！
@JayWii 好

**Comment by xaoxuu** [comment]
大神你好，请问底图怎么引用外链图片？

**Comment by SIGAOYI** [comment]
@xaoxuu 请见 issues #40

**Comment by xaoxuu** [comment]
@SIGAOYI 非常感谢，已解决
