### ISSUE TITLE
Is there a posibility that bootstrap maintains the whole responsive function rather than do it on my own

### ISSUE THREAD

**Issue by decaywood** [Huxpro/huxpro.github.io#60]
when i check out the *-blog.less file, i saw the content just like this:@media screen and (max-width: 768px), can I replace it with bootstrap's class? it may be more maintainable...

**Comment by Huxpro** [comment]
@decaywood Well, you can absolutely do that!
But, I dont get your points clearly. What kind of bootstrap's class did you mean? As far as I know the responsive utilities provided only do some visible/hidden stuff but our own media queries serve more obviously.

**Comment by decaywood** [comment]
actually,i dun know the css stuff,just want to seek the way to refactored the code structure. simpleness is always the best : ),  i think the difference of UI between PC and cellphone or pad can be controlled by bootstrap? or did i miss sth?

**Comment by Huxpro** [comment]
@decaywood Bootstrap is not the silver bullet. 
Although it provide great grid system and responsive utils, which are both actively used by hux-blog, there is still a great many of responsive feature it missing. If you wanna more device experiences, go and get your hands dirty.

**Comment by decaywood** [comment]
thanks for ur answer ; ) it seems that bootstrap isn't what i expect to be...
