### ISSUE TITLE
用连续#表示的标题会多出一个#

### ISSUE THREAD

**Issue by shaoguoji** [Huxpro/huxpro.github.io#61]
生成后的网站 markdwon 语法的不同级标题的表示会多一个#，有强迫症的同学表示好纠结~~~

**Comment by shaoguoji** [comment]
是不是与文章内自动生成目录的功能有关

**Comment by blurrye** [comment]
不请自来，
_layouts/post.html中246行 icon: '#'
去掉#就行了。

**Comment by shaoguoji** [comment]
回复blurrye ，删掉#还不行，要把单引号也删了，就好咯哈哈

**Comment by Huxpro** [comment]
@shaoguoji @blurrye 

Hey guys, 这里有一个重复的 issue: <https://github.com/Huxpro/huxpro.github.io/issues/54>

会在标题旁多个 # 号，是因为使用了 anchor.js 来给每个标题增加一个“可以点击的锚点”，用以在分享时可以直接跳转到某个标题。在 _config.yml 中可以直接设置关掉哦。

**Comment by shaoguoji** [comment]
@Huxpro 没看到抱歉，谢谢你的回复~~~
