### ISSUE TITLE
jekyll serve failed ''cannot load such file -- jekyll-paginate“

### ISSUE THREAD

**Issue by shaoguoji** [Huxpro/huxpro.github.io#62]
When I use "jekyll serve" to preview my blog, I got flowing erro：

Configuration file: C:/Users/jjj/Documents/GitHub/shaoguoji.github.io/_config.yml
C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- jekyll-pagina
te (LoadError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:30:in `block in require_ge
ms'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:27:in `require_gems'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:19:in `conscientious_requi
re'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in
 init_with_program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
        from C:/Ruby22-x64/bin/jekyll:23:in `load'
        from C:/Ruby22-x64/bin/jekyll:23:in `<main>'

After update the jekyll and run jekyll again, I got another erro:

Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/!

jekyll 3.1.1 | Error: jekyll-paginate

**Comment by shaoguoji** [comment]
According to this question in stackoverflow: "http://stackoverflow.com/questions/35401566/dont-have-jekyll-paginate-or-one-of-its-dependencies-installed", I slove my problem. 

Just two step:"First run 'gem uninstall --all', then run 'gem install github-pages'",

**Comment by Huxpro** [comment]
@shaoguoji neat!

**Comment by ehsong** [comment]
I still have the error, and I don't know how to trouble shoot:
you don't have jekyll-paginate or one of its dependencies installed

**Comment by yeominstall** [comment]
Hi, I simply modify `Gemfile` when I had a same problem. I add `jekyll-paginate` to plugins like below:

```
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12.1"
  gem "jekyll-seo-tag", "~> 2.6.1"
  gem "jekyll-paginate", "~> 1.1.0"
end
```

HTH

**Comment by rowe-morehouse** [comment]
try:

`bundle exec jekyll serve`

instead of:

`jekyll serve`
