### ISSUE TITLE
MathJax Support

### ISSUE THREAD

**Issue by Voleking** [Huxpro/huxpro.github.io#63]
Hi, I would like to make a pull request to make this blog support [MathJax](https://www.mathjax.org) to make beautiful formulas in posts.However, I wonder which way you prefer more:   
1.  Just add the javascript(?) in the __layouts/default.html_ thus can use it in most place of the blog
2.  Create a file named with _mathjax_support_ in your __include_ directory and finally use a variable _use_math_ and set its value to true to use it in some post if necessary.

By the way, you can also make this change on your own by reference [this](http://haixing-hu.github.io/programming/2013/09/20/how-to-use-mathjax-in-jekyll-generated-github-pages/).

**Comment by LucasIcarus** [comment]
Using a variable would be nice, I think. With format like {% if... %}... in the footer.html to load js works well I think? Haven't read the reference though, :).

**Comment by Huxpro** [comment]
It's weird that my replied email did not display here:

> @voleking Thanks in advance! It would be a great feature!
> I definitely prefer the second approach which decrease the payload of every math-unrelated  post ;)

Thanks @LucasIcarus ;)

**Comment by voleking** [comment]
@LucasIcarus @Huxpro Thx, I got it. Since there are some small issues, I hope I could fix it before I pull.Maybe it take a little time.

**Comment by voleking** [comment]
I'm sorry to say that because of terrible midterm exams, I don't have a time make this change until May 10th.

**Comment by Huxpro** [comment]
@voleking yeah it's ok~
