### ISSUE TITLE
模板的clone方式

### ISSUE THREAD

**Issue by allanruin** [Huxpro/huxpro.github.io#64]
首页写的是`git clone git@github.com:Huxpro/huxblog-boilerplate.git` ，但这样其实没有权限，会被拒绝的。建议改成 `git clone https://github.com/Huxpro/huxblog-boilerplate.git`。

因为只是一个小的修改，我就不fork和pull了~

**Comment by Huxpro** [comment]
@allanruin  第一种方式使用的是 SSH，如果没权限的话是你本机的问题；
不过 github 现在确实 recommend HTTPS 的方式

**Comment by allanruin** [comment]
好的，可能确实是我的证书问题。最近在coding.net和github之间还有不同电脑和虚拟机之间都有用到git，确实有点混乱了:)
