### ISSUE TITLE
boilerplate生成页面img路径问题

### ISSUE THREAD

**Issue by allanruin** [Huxpro/huxpro.github.io#65]
直接clone boilerplate下来，启动serve， 发现avatar的img无法显示的。因为在config文件里绝对路径硬编码了`/img/avatar-hux.jpg` 所以当有`baseurl: "/huxblog-boilerplate"`时访问的地址就不对了。

![hux_img_path_problem](https://cloud.githubusercontent.com/assets/1366627/14578945/84629c52-03cb-11e6-9a24-85e35c2bb5f6.png)

**Comment by Huxpro** [comment]
@allanruin 

```
#_config.yml 
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
```

为了不混淆 absolute URL 的定义，这一个配置项并没有兼容需要 baseurl 的情景。换句话说，如果你需要使用 baseurl，那么请在这里自行写上。

至于我在这里使用 img/avatar-hux.jpg，是因为我的 root 下确实存在这个静态文件；

不过，为了避免让更多的人 confuse，这个确实需要修改或补充，感谢 report！
