### ISSUE TITLE
Create Archive

### ISSUE THREAD

**Issue by banpie** [Huxpro/huxpro.github.io#67]

**Comment by Huxpro** [comment]
@devmidai 能详细描述下你的目录页指的是什么吗

**Comment by devmidai** [comment]
就是我们常见的archive那个页面，里面按照发布的日期把所有文章都罗列出来，目前的模版比较不方便的是，翻看历史文章。

**Comment by Huxpro** [comment]
@devmidai https://github.com/Huxpro/huxpro.github.io/issues/22

**Comment by Huxpro** [comment]
@devmidai  可以参考 @BruceZhaoR  的实现：http://brucezhaor.github.io/archives/

**Comment by BruceZhaoR** [comment]
代码参考别人的文章修改过一次，不再是  #22  里面代码了，具体看这里: <https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/archives.html> 
改一下我的 `{{ BASE_PATH }}` , 应该直接贴过去就能用的。

**Comment by voleking** [comment]
@devmidai  也可以参考下我的，虽然比较搓：  https://github.com/voleking/voleking.github.io/blob/master/archive.md

**Comment by devmidai** [comment]
好的 谢！

发自我的 iPhone

**Comment by Huxpro** [comment]
A new Archive page is introduced at [V1.8](https://github.com/Huxpro/huxpro.github.io#v18)!
