### ISSUE TITLE
baseurl issue

### ISSUE THREAD

**Issue by Voleking** [Huxpro/huxpro.github.io#70]
If I add baseurl simply like this in _config.yml_ file :

```
baseurl: "/blog"                             # for example, '/blog' if your blog hosted on 'host/blog'
```

There will be something wrong such as js/jquery.tagcloud.js not found and so on, you can have test;)

**Comment by Huxpro** [comment]
@Voleking 
God...I always miss `baseurl` stuff. Yep I convinced It's a bug. Thx for your report.
To make things better, maybe you can help me fixed it?

**Comment by Voleking** [comment]
@Huxpro 
Well, It's a thorny issue for a layman like me. Maybe I could have a try after I know more things about front end.But now I am regret to say I could do nothing.

**Comment by Kaijun** [comment]
fiexd. check the new commit 66db488b6fb4cc9d8c061b8ab0b9732ab801c99a

**Comment by Voleking** [comment]
@Kaijun Well Done! Thx a lot.
