### ISSUE TITLE
当点击文章内部的 tag 时, 跳转到只包含页头和页脚的空白页面

### ISSUE THREAD

**Issue by ehazon** [Huxpro/huxpro.github.io#75]

**Comment by ehazon** [comment]
sorry , I'm post wrong ,  in fact  I'm try post issue to [Kaijun](https://github.com/Kaijun) , hope you don' mind

**Comment by bigpineapple2333** [comment]
这边遇到了同样的问题，包括点击主页中上方导航栏archives一项也是空白页面，翻了一上午代码也没看出来哪里不对劲。后尝试使用作者的稳定版模板中的tags.html代码，可以解决问题。但是好像还是比较喜欢作者大大现在的archives页面。不知是否能请大佬瞟一眼是怎么回事，万分感谢。这里是链接：https://bigpineapple2333.github.io/
