### ISSUE TITLE
能不能加上LaTeX支持？

### ISSUE THREAD

**Issue by Airtnp** [Huxpro/huxpro.github.io#78]
用MathJax之类的？

**Comment by Airtnp** [comment]
搜索了一下，kramdown应该内置mathjax支持，且默认公式输入为`$$...$$`
但是·$x^2$·显示·$x^2$`   ·$$x^2$$` 不显示

**Comment by Airtnp** [comment]
似乎[Mathjax, kramdown and Octopress](https://www.lucypark.kr/blog/2013/02/25/mathjax-kramdown-and-octopress/) 可以解决 
[pull request](https://github.com/Huxpro/huxpro.github.io/pull/79)

**Comment by BruceZhaoR** [comment]
我也用的是MathJax的在线js,效果还可以。

**Comment by Huxpro** [comment]
Done via [V1.8](https://github.com/Huxpro/huxpro.github.io#v18)
