### ISSUE TITLE
非常感谢LZ的模板

### ISSUE THREAD

**Issue by Allianzcortex** [Huxpro/huxpro.github.io#8]
呐……就是这样。LZ的双列模板实在是太棒了。

我比较喜欢上列留白，再加上对Bootstrap导航栏的疯狂热爱，做成了这样的一种情况[hz | blog](allianzcortex.github.io)。总的设计思路是主页只保留有关技术的文章，其他杂谈在导航栏
里，不主动推送。

---

在page.html里引入bootstrap.min.css之后感觉字体不太好，想换用**微软雅黑**，但chrome里提示一直没有被使用，还是默认的字体。还有一些链接没有处理。都是一些小的problem，毕竟也不是专业前端，就这样吧……之后有机会再改。

新增加了 date.html，用来存放Archive，按照日期列表来存储文章。

---

在blog.css里关于label{}的情况，颜色是否应该用background-color:，仅仅用color无法改变标签的背景色。

---

还有一个小建议是在文档里增加**修改多说评论和百度统计的文档**。要不就会有很多莫名其妙的评论，sigh:-)

**Comment by Allianzcortex** [comment]
地址好像不对？http://allianzcortex.github.io/

**Comment by jincan39** [comment]
=。=宽屏看着怎么这么怪 原生的bootstrap twitter主题么

**Comment by Allianzcortex** [comment]
@jincan39 怪是指？当时设立顶部空白的目的是在浏览到网页的任何位置都可以直接点击回到主界面。导航栏是我比较偏好的一部分。感觉还好吧

**Comment by Huxpro** [comment]
@Allianzcortex Hey, thanks for your nice words.

我觉得“主页只保留有关技术的文章，其他杂谈在导航栏” 的思路很不错。

关于 Bootstrap 导航栏的问题，我建议你查阅这个 [commit](https://github.com/Huxpro/huxpro.github.io/commit/dfe059f2081aff0cb58479e23d73123e3cecb237) ，我在这个  commit 中将 Bootstrap 的导航修改成了自己的，你可以逆向回来。

关于其他样式问题，最好贴上比较细致的描述，不然我很难帮助到你～

“在文档里增加修改多说评论和百度统计的文档” 是个好建议，确实有这个问题存在

Thanks

**Comment by Allianzcortex** [comment]
@Huxpro 之前自己的博客主题用的是Disqus,但最后还是觉得国内就用**多说**吧，不会有加载不出来的情况。LZ履历和写的文章都好棒，有机会到帝都一定要见一面:-)

**Comment by Huxpro** [comment]
@Allianzcortex 的确是这样，我个人也很喜欢Disqus，但是国内实在是没有办法……

另外，我发布了 v1.5 版本，将多说、百度统计、Google Analytics 全面内置并且可以作为配置项了，文档也全面更新，如果需要，可以 fetch 下来手动 merge 一下

**Comment by Allianzcortex** [comment]
@Huxpro ,好高的效率，非常好的分离

---

我是在post和board里加载了评论选项，page和其他的index.html没有加载

---

昨天试着在移动端加载了一下，感觉还好。就是背景图片加载不出来，应该是太大了(4M)，考虑用PS调低一下分辨率;-)

---

**close the issue** is possible ;-)

**Comment by Huxpro** [comment]
@Allianzcortex 噗，别用这么大的图片啊……＝＝！

All right, thanks for all your nice advice, I'll close this issue.
