### ISSUE TITLE
多说的使用流程

### ISSUE THREAD

**Issue by huangxunyi** [Huxpro/huxpro.github.io#85]
请问多说分享和评论 要改哪些代码才能正常使用

**Comment by Inblac** [comment]
_config.yml 里的 duoshuo_username，改成自己申请的多说ID
about.html里面 中间有一段好像也要改，没看太懂。
post.html没有修改，layout选post的话，新博文发出来就可以评论了。

**Comment by Huxpro** [comment]
@Inblac @huangxunyi 只要改 duoshuo_username 即可
