### ISSUE TITLE
Local preview with the actual situation is different

### ISSUE THREAD

**Issue by LostOnion** [Huxpro/huxpro.github.io#87]
I use this template, the local operation is correct, but the style is lost on the github pages.
and here is my page ,http://lostonion.github.io/ 

all of my files have push to master branch,The official tutorial show me . must create a gh-page branch.

Is this necessary?

**Comment by BruceZhaoR** [comment]
@LostOnion 

1. Your repository is `lostonion.github.io`,so you don't need to ceate a gh-page branch.

2. You need to set something below in your `_config.yml` file

```
url: http://lostonion.github.io
baseurl: "" 
```
I recommend you read the [README](https://github.com/Huxpro/huxpro.github.io/blob/master/README.md) carefully. The [jekyll official website](http://jekyllrb.com/) may be helpful.

Also, if you use Chrome ,the F12 may help you to find the problem. Good luck! :blush:

**Comment by LostOnion** [comment]
I made a mistake , F12 help me . I thought I must set a not empty string to baseurl 
how about change the tip form 

> # for example, '/blog' if your blog hosted on 'host/blog'
 to 

> for example, '/blog' if your blog hosted on 'host/blog' IF you use this Boilerplate for your page without a secondary domain name ,make it empty .

Just for newbies  without any statice pages 'exp . like me
