### ISSUE TITLE
为什么我使用的多说评论不能加载样式？

### ISSUE THREAD

**Issue by jakciehoo** [Huxpro/huxpro.github.io#89]
这是我的提示：
http://jackiehoo.duoshuo.com/api/threads/listPosts.json?thread_key=%2F2016%…%2Cunread%2Clog%2CextraCss&referer=http%3A%2F%2Fjackiehoo.com%2F&v=16.6.16 Failed to load resource: the server responded with a status of 400 (Bad Request)
static.duoshuo.com/embed.js:1 出错啦(990002): 参数错误l @ static.duoshuo.com/embed.js:1

我怀疑我的多说用户名参数输入不对。
duoshuo_username ： jackeihoo
这个名称是用微博注册多说后，修改的用户名，这样对吗

**Comment by BruceZhaoR** [comment]
@jakciehoo 
http://jackeihoo.duoshuo.com/admin/  能打开吗?  参考里面的说明进行设置.

**Comment by khadgarmage** [comment]
@BruceZhaoR 你给的链接地址打不开，提示页面不存在

**Comment by BruceZhaoR** [comment]
@khadgarmage   你要先注册一个账号啊：   http://duoshuo.com/create-site/   

比如我就可以直接去这里管理我的后台评论数据 http://brucezhaor.duoshuo.com/admin/
