### ISSUE TITLE
footer的图标消失，http的css在https的github.io上被屏蔽

### ISSUE THREAD

**Issue by Shawkaine** [Huxpro/huxpro.github.io#93]
本地预览正常
![sd3](https://cloud.githubusercontent.com/assets/10775888/16706771/5e0b87a0-45eb-11e6-929f-85b9ba5428a5.png)
线上消失

![sd](https://cloud.githubusercontent.com/assets/10775888/16706902/72be13c0-45f0-11e6-9dea-608905d31c1f.png)

[博客](https://shawkaine.github.io/)

**Comment by LucasIcarus** [comment]
那个iframe显示github repo 和星星数量的部分嘛?

**Comment by Shawkaine** [comment]
@LucasIcarus sidebar和footer都有的sns外链， 知乎、Github、Facebook的图标，对比图或者去我博客也看得到。

**Comment by LucasIcarus** [comment]
@Shawkaine SNS的话应该是fontawsome.css没加载上  审查元素看一下样式就知道了..

**Comment by Shawkaine** [comment]
@LucasIcarus 醉了，`Mixed Content: The page at 'https://shawkaine.github.io/' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css'. This request has been blocked; the content must be served over HTTPS.`   因为不是https被屏蔽了！这怎么办

**Comment by LucasIcarus** [comment]
@Shawkaine 把那个cdn改成https开头的应该就好了吧

**Comment by Shawkaine** [comment]
谢谢，不过我换成本地资源了……

**Comment by GilGuan** [comment]
请问下在哪里能修改？

**Comment by LucasIcarus** [comment]
@GilGuan  在https://github.com/Huxpro/huxpro.github.io/blob/master/_includes/head.html

**Comment by GilGuan** [comment]
@LucasIcarus Thanks.
