### ISSUE TITLE
为什么我打开_site里面的index.html的网页是没有图片没有排版的，但是执行jekyll server就行

### ISSUE THREAD

**Issue by kuhippo** [Huxpro/huxpro.github.io#98]
应该很多人有这个问题吧，请问你们怎解决的，哈哈不会html，弄了我好久

**Comment by BruceZhaoR** [comment]
解决方法很简单, 打开index.html  将 `/css/... `   还有 `/js` 这样的路径改为相对地址就能本地直接打开 index.html了. 

问题的关键是你的素材**没有**加载进来, 你需要调整 **外链素材**的**地址链接**.
